// Unit testbench: pw_flow_gen_multi encapsulation TX construction. Four flow
// slots exercise the encap matrix (IPIP / GRE / EtherIP, with v4 and v6 inner
// and outer). The parser does not yet decapsulate (separate task), so this tb
// validates the GENERATED BYTES directly: outer Ethernet/IP, the tunnel header,
// the inner IP header, the inner UDP checksum (v6) and the test header at its
// (encap-dependent) deep offset.
`default_nettype none

import pw_axis_pkg::*;
import pw_classifier_pkg::*;

module tb_flow_gen_encap;
    localparam int SLOTS = 4;

    logic clk = 0, rst_n = 0;
    always #5 clk = ~clk;
    logic [63:0] ts = 0;

    pw_flow_row_t f_rows [SLOTS];
    logic [63:0] td; logic [7:0] tk; logic tv, tl;

    // Model the BRAM-backed flow table (compact sched array + 1-cycle row read).
    pw_flow_sched_t f_sched [SLOTS];
    always_comb for (int s = 0; s < SLOTS; s++) begin
        f_sched[s] = '0;
        f_sched[s].valid     = f_rows[s].valid;
        f_sched[s].egress    = f_rows[s].egress;
        f_sched[s].tokens_fp = f_rows[s].tokens_fp;
        f_sched[s].cap       = {f_rows[s].burst, 16'h0};
        f_sched[s].cost      = {16'(pw_frame_bytes(f_rows[s], 32)), 16'h0};
    end
    logic [$clog2(SLOTS)-1:0] rd_addr;
    pw_flow_row_t             rd_row;
    logic [47:0]              gtxc [SLOTS];
    always_ff @(posedge clk) rd_row <= f_rows[rd_addr];

    pw_flow_gen_multi #(.EGRESS_PORT(0), .NUM_SLOTS(SLOTS), .FRAME_LEN_PAYLOAD(32)) gen (
        .clk(clk), .rst_n(rst_n), .timestamp_i(ts),
        .flow_sched_i(f_sched), .rd_addr_o(rd_addr), .rd_row_i(rd_row),
        .stats_clear_i(1'b0), .tx_count_o(gtxc),
        .m_tdata(td), .m_tkeep(tk), .m_tvalid(tv), .m_tready(1'b1), .m_tlast(tl)
    );

    // End-to-end RX check: the parser must decapsulate each tunnel and recover
    // the inner test header (is_test + flow_id) -- proving TX/decap agree.
    pw_match_key_t key; logic key_valid;
    pw_parser_axis dut (
        .clk(clk), .rst_n(rst_n),
        .s_tdata(td), .s_tkeep(tk), .s_tvalid(tv), .s_tready(), .s_tlast(tl),
        .ingress_port_i(4'd0), .rx_wire_ts_i(64'd0),
        .key_o(key), .key_valid_o(key_valid), .rx_wire_ts_o(), .window_o(), .base_o()
    );
    // Track which inner flow_ids the parser recovered as test frames.
    logic seen10 = 0, seen11 = 0, seen12 = 0, seen13 = 0;
    always_ff @(posedge clk) begin
        if (rst_n && key_valid && key.is_test) begin
            if (key.test_flow_id == 32'd10) seen10 <= 1'b1;
            if (key.test_flow_id == 32'd11) seen11 <= 1'b1;
            if (key.test_flow_id == 32'd12) seen12 <= 1'b1;
            if (key.test_flow_id == 32'd13) seen13 <= 1'b1;
        end
    end

    int g_pass = 0, g_fail = 0;
    task chk(input string n, input logic c);
        if (c) begin g_pass++; $display("[ ok ] %s", n); end
        else   begin g_fail++; $display("[FAIL] %s", n); end
    endtask

    localparam logic [31:0] MAGIC = 32'hA502_7E57;

    // Per-frame capture: assemble each frame, then route it to the matching
    // encap slot's buffer (first frame only) by outer signature.
    logic [7:0] fb [0:255]; int fb_n = 0;
    logic [7:0] c_ipip44 [0:255]; int n_ipip44 = 0; logic d_ipip44 = 0;
    logic [7:0] c_ipip66 [0:255]; int n_ipip66 = 0; logic d_ipip66 = 0;
    logic [7:0] c_gre    [0:255]; int n_gre    = 0; logic d_gre    = 0;
    logic [7:0] c_eip    [0:255]; int n_eip    = 0; logic d_eip    = 0;

    always_ff @(posedge clk) begin
        ts <= ts + 1;
        if (rst_n && tv) begin
            for (int k = 0; k < 8; k++) if (tk[k]) begin
                if (fb_n < 256) fb[fb_n] = td[k*8 +: 8];
                fb_n++;
            end
            if (tl) begin
                // classify by outer ethertype + outer proto/next-header
                if (fb[12] == 8'h08 && fb[13] == 8'h00 && fb[23] == 8'd4 && !d_ipip44) begin
                    for (int i = 0; i < 256; i++) c_ipip44[i] = fb[i];
                    n_ipip44 = fb_n; d_ipip44 <= 1'b1;
                end
                if (fb[12] == 8'h86 && fb[13] == 8'hDD && fb[20] == 8'd41 && !d_ipip66) begin
                    for (int i = 0; i < 256; i++) c_ipip66[i] = fb[i];
                    n_ipip66 = fb_n; d_ipip66 <= 1'b1;
                end
                if (fb[12] == 8'h86 && fb[13] == 8'hDD && fb[20] == 8'd47 && !d_gre) begin
                    for (int i = 0; i < 256; i++) c_gre[i] = fb[i];
                    n_gre = fb_n; d_gre <= 1'b1;
                end
                if (fb[12] == 8'h08 && fb[13] == 8'h00 && fb[23] == 8'd97 && !d_eip) begin
                    for (int i = 0; i < 256; i++) c_eip[i] = fb[i];
                    n_eip = fb_n; d_eip <= 1'b1;
                end
                fb_n = 0;
            end
        end
    end

    // IPv4 header checksum check over `n` words starting at byte `o`.
    function automatic logic ip_csum_ok(input logic [7:0] b [0:255], input int o);
        logic [31:0] s; s = 0;
        for (int w = 0; w < 10; w++) s += {b[o + w*2], b[o + w*2 + 1]};
        s = (s & 32'hFFFF) + (s >> 16);
        s = (s & 32'hFFFF) + (s >> 16);
        return (s[15:0] == 16'hFFFF);
    endfunction
    // test-header magic match at deep offset `o`.
    function automatic logic magic_ok(input logic [7:0] b [0:255], input int o);
        return b[o]   == MAGIC[31:24] && b[o+1] == MAGIC[23:16]
            && b[o+2] == MAGIC[15:8]  && b[o+3] == MAGIC[7:0];
    endfunction

    task automatic mkrow(input int s, input logic [31:0] fid,
                         input logic inner_v6, input logic [1:0] et, input logic outer_v6);
        f_rows[s] = '0;
        f_rows[s].valid    = 1'b1;
        f_rows[s].egress   = 4'd0;
        f_rows[s].flow_id  = fid;
        f_rows[s].tokens_fp = 32'h0010_0000;     // 16 B/cycle -> emits steadily
        f_rows[s].burst    = 16'd4096;
        f_rows[s].src_mac  = 48'h02a5_0200_0001;
        f_rows[s].dst_mac  = 48'h02a5_0200_0002;
        f_rows[s].src_ipv4 = 32'hC000_0201;       // 192.0.2.1
        f_rows[s].dst_ipv4 = 32'hC000_0202;       // 192.0.2.2
        f_rows[s].udp_sp   = 16'd49152;
        f_rows[s].udp_dp   = 16'd50001;
        f_rows[s].ttl      = 8'd64;
        f_rows[s].is_v6    = inner_v6;
        f_rows[s].ipv6_src = 128'h2001_0db8_0000_0000_0000_0000_0000_0001;
        f_rows[s].ipv6_dst = 128'h2001_0db8_0000_0000_0000_0000_0000_0002;
        f_rows[s].encap_type = et;
        f_rows[s].outer_v6   = outer_v6;
        f_rows[s].outer_ttl  = 8'd32;
        f_rows[s].outer_dscp = 8'd0;
        f_rows[s].outer_src_ipv4 = 32'h0A00_0001;  // 10.0.0.1
        f_rows[s].outer_dst_ipv4 = 32'h0A00_0002;  // 10.0.0.2
        f_rows[s].outer_ipv6_src = 128'hFE80_0000_0000_0000_0000_0000_0000_0001;
        f_rows[s].outer_ipv6_dst = 128'hFE80_0000_0000_0000_0000_0000_0000_0002;
        // Distinct inner-Ethernet MAC (EtherIP) -- 0xBB marker proves the inner
        // header carries the inner MAC, not the outer flow MAC (0xA5).
        f_rows[s].inner_dst_mac = 48'h02bb_0000_0002;
        f_rows[s].inner_src_mac = 48'h02bb_0000_0001;
    endtask

    initial begin
        for (int s = 0; s < SLOTS; s++) f_rows[s] = '0;
        // slot 0: IPIP, v4 inner in v4 outer
        mkrow(0, 32'd10, 1'b0, 2'd1, 1'b0);
        // slot 1: IPIP, v6 inner in v6 outer
        mkrow(1, 32'd11, 1'b1, 2'd1, 1'b1);
        // slot 2: GRE, v4 inner in v6 outer
        mkrow(2, 32'd12, 1'b0, 2'd2, 1'b1);
        // slot 3: EtherIP, v4 inner in v4 outer
        mkrow(3, 32'd13, 1'b0, 2'd3, 1'b0);

        repeat (4) @(posedge clk); rst_n = 1;
        repeat (4000) @(posedge clk);

        // ---- IPIP v4-in-v4: eth(14)+outerIPv4(20,proto4)+innerIPv4(20)+UDP+pl ----
        chk("ipip44 captured", d_ipip44);
        chk("ipip44 frame length 94", n_ipip44 == 94);
        chk("ipip44 outer ethertype 0800", c_ipip44[12]==8'h08 && c_ipip44[13]==8'h00);
        chk("ipip44 outer ver/ihl 0x45", c_ipip44[14]==8'h45);
        chk("ipip44 outer proto 4", c_ipip44[23]==8'd4);
        chk("ipip44 outer ttl 32", c_ipip44[22]==8'd32);
        chk("ipip44 outer src 10.0.0.1", c_ipip44[26]==8'd10 && c_ipip44[29]==8'd1);
        chk("ipip44 outer csum valid", ip_csum_ok(c_ipip44, 14));
        chk("ipip44 inner ver/ihl 0x45", c_ipip44[34]==8'h45);
        chk("ipip44 inner proto 17", c_ipip44[43]==8'd17);
        chk("ipip44 inner src 192.0.2.1", c_ipip44[46]==8'd192 && c_ipip44[49]==8'd1);
        chk("ipip44 inner csum valid", ip_csum_ok(c_ipip44, 34));
        chk("ipip44 test magic @62", magic_ok(c_ipip44, 62));

        // ---- IPIP v6-in-v6: eth+outerIPv6(40,nh41)+innerIPv6(40)+UDP+pl=134 ----
        chk("ipip66 captured", d_ipip66);
        chk("ipip66 frame length 134", n_ipip66 == 134);
        chk("ipip66 outer ethertype 86DD", c_ipip66[12]==8'h86 && c_ipip66[13]==8'hDD);
        chk("ipip66 outer version 6", c_ipip66[14][7:4]==4'h6);
        chk("ipip66 outer next-hdr 41", c_ipip66[20]==8'd41);
        chk("ipip66 outer hop limit 32", c_ipip66[21]==8'd32);
        chk("ipip66 inner version 6", c_ipip66[54][7:4]==4'h6);
        chk("ipip66 inner next-hdr 17", c_ipip66[60]==8'd17);
        chk("ipip66 test magic @102", magic_ok(c_ipip66, 102));

        // ---- GRE v4-in-v6: eth+outerIPv6(40,nh47)+GRE(4)+innerIPv4(20)+UDP+pl=118 -
        chk("gre captured", d_gre);
        chk("gre frame length 118", n_gre == 118);
        chk("gre outer ethertype 86DD", c_gre[12]==8'h86 && c_gre[13]==8'hDD);
        chk("gre outer next-hdr 47", c_gre[20]==8'd47);
        chk("gre header flags/ver 0", c_gre[54]==8'h00 && c_gre[55]==8'h00);
        chk("gre proto-type 0800", c_gre[56]==8'h08 && c_gre[57]==8'h00);
        chk("gre inner ver/ihl 0x45", c_gre[58]==8'h45);
        chk("gre inner csum valid", ip_csum_ok(c_gre, 58));
        chk("gre test magic @86", magic_ok(c_gre, 86));

        // ---- EtherIP v4-in-v4: eth+outerIPv4(20,proto97)+EtherIP(2)+innerEth(14)
        //      +innerIPv4(20)+UDP+pl = 110 ----
        chk("etherip captured", d_eip);
        chk("etherip frame length 110", n_eip == 110);
        chk("etherip outer proto 97", c_eip[23]==8'd97);
        chk("etherip outer csum valid", ip_csum_ok(c_eip, 14));
        chk("etherip version 0x3000", c_eip[34]==8'h30 && c_eip[35]==8'h00);
        // inner-eth dmac = 02:bb:00:00:00:02 (distinct inner MAC, not outer 02:a5..)
        chk("etherip inner eth dmac (inner MAC)", c_eip[36]==8'h02 && c_eip[37]==8'hbb && c_eip[41]==8'h02);
        chk("etherip inner eth smac (inner MAC)", c_eip[42]==8'h02 && c_eip[43]==8'hbb && c_eip[47]==8'h01);
        chk("etherip inner eth ethertype 0800", c_eip[48]==8'h08 && c_eip[49]==8'h00);
        chk("etherip inner ver/ihl 0x45", c_eip[50]==8'h45);
        chk("etherip inner csum valid", ip_csum_ok(c_eip, 50));
        chk("etherip test magic @78", magic_ok(c_eip, 78));

        // ---- RX decap: parser recovered the inner test header of each tunnel -
        chk("decap recovered ipip44 inner flow_id 10", seen10);
        chk("decap recovered ipip66 inner flow_id 11", seen11);
        chk("decap recovered gre   inner flow_id 12", seen12);
        chk("decap recovered etherip inner flow_id 13", seen13);

        $display("flow_gen_encap: (%0d pass, %0d fail)", g_pass, g_fail);
        if (g_fail == 0) $display("ALL FLOW_GEN_ENCAP SCENARIOS PASS");
        else $display("FAILED with %0d error(s)", g_fail);
        $finish;
    end
endmodule
`default_nettype wire
