/* packetwyrm-proxyd: TLS-terminating HTTPS gateway for the PacketWyrm Web GUI
 * and remote CLI.
 *
 * This is a *stateless relay*, deliberately separate from packetwyrmd:
 *   [browser / pktwyrm --host] --HTTPS--> [packetwyrm-proxyd]
 *                                              |
 *                                     Unix socket (4B len + JSON)
 *                                              v
 *                                        [packetwyrmd]
 *
 * It serves the embedded single-page GUI (GET /) and forwards
 * `POST /api/rpc` request bodies verbatim onto the daemon's control
 * socket, returning the daemon's JSON reply. It does NOT parse or
 * understand the RPC payload and holds no shared state with the daemon,
 * so it cannot stall the daemon's single-threaded control/servo loop.
 *
 * Authentication is unchanged: the daemon remains the sole authority.
 * The client puts its `"secret"` in the JSON body; we forward it as-is;
 * the daemon does the constant-time compare. This gateway needs no
 * knowledge of the secret. See docs/design/web-gui.md.
 */
#include <arpa/inet.h>
#include <errno.h>
#include <netinet/in.h>
#include <pthread.h>
#include <signal.h>
#include <stdatomic.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>

#include <openssl/err.h>
#include <openssl/evp.h>
#include <openssl/pem.h>
#include <openssl/ssl.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>

#include "packetwyrm/ipc.h"
#include "packetwyrm/packetwyrm.h"

/* Embedded GUI asset tree (generated by gen_assets.py in the Makefile):
 * `struct pw_asset pw_assets[]` = { url path, bytes, len, content-type }. */
#include "proxyd_assets.h"

/* Content-Security-Policy for served pages/assets. Everything is same-origin
 * (no CDN); default-src 'self' blocks external loads. The GUI JS is fully
 * externalised into ES modules under /js, so script-src is 'self' (no inline
 * script). style-src keeps 'unsafe-inline' for the GUI's dynamic style=
 * (bar widths etc.); those inline styles are values, not scripts. */
#define PROXYD_CSP \
    "default-src 'self'; " \
    "script-src 'self'; " \
    "style-src 'self' 'unsafe-inline'; " \
    "img-src 'self' data:; connect-src 'self'; " \
    "object-src 'none'; base-uri 'none'; frame-ancestors 'none'"

#define PROXYD_DEFAULT_LISTEN "0.0.0.0:8443"
#define PROXYD_DEFAULT_PORT   8443
#define PROXYD_MAX_THREADS     32
#define PROXYD_REQ_MAX         (PW_IPC_FRAME_MAX + 8192) /* headers + body */
/* Wall-clock budget for reading ONE request (headers + body). SO_RCVTIMEO
 * only bounds a single read(); without this a Slowloris client trickling
 * one byte per <15 s holds a worker forever, and 32 of them exhaust
 * PROXYD_MAX_THREADS. */
#define PROXYD_REQ_DEADLINE_S  30
/* How long a successful daemon-secret probe stays fresh on a non-loopback
 * bind before /api/rpc re-confirms it (see auth_probe_current()). */
#define PROXYD_PROBE_PERIOD_S  60

struct proxyd_opts {
    const char *listen_addr;   /* IPv4 dotted address to bind */
    int         listen_port;
    const char *daemon_sock;
    const char *tls_cert;      /* NULL -> auto self-signed */
    const char *tls_key;
    bool        no_tls;        /* plaintext HTTP (localhost / SSH tunnel) */
    bool        insecure_no_auth;
    const char *allowed_hosts; /* extra Host header values, comma-separated */
};

/* Shared, read-only after startup: safe to touch from worker threads. */
static SSL_CTX          *g_ssl_ctx;      /* NULL when --no-tls */
static const char       *g_daemon_sock;
static const char       *g_listen_addr;    /* bound address (numeric IPv4) */
static char            **g_allowed_hosts;  /* NULL-terminated, may be NULL */
static _Atomic int       g_active_threads;

/* Auth re-probe state (non-loopback binds only), see auth_probe_current(). */
static bool             g_probe_enforce;   /* non-loopback && !--insecure-no-auth */
static pthread_mutex_t  g_probe_mu = PTHREAD_MUTEX_INITIALIZER;
static bool             g_probe_ok_valid;  /* g_probe_ok_ts holds a pass */
static struct timespec  g_probe_ok_ts;     /* CLOCK_MONOTONIC of last pass */

/* ------------------------------------------------------------------ */
/* TLS setup                                                          */
/* ------------------------------------------------------------------ */

static void print_fingerprint(X509 *x) {
    unsigned char md[EVP_MAX_MD_SIZE];
    unsigned int n = 0;
    if (X509_digest(x, EVP_sha256(), md, &n) != 1) return;
    fputs("  TLS cert SHA-256: ", stdout);
    for (unsigned i = 0; i < n; i++)
        printf("%02X%s", md[i], (i + 1 < n) ? ":" : "");
    putchar('\n');
}

/* Generate an in-memory self-signed EC (P-256) certificate and load it
 * into `ctx`. Browsers will warn (self-signed); the printed fingerprint
 * lets an operator verify. */
static int tls_self_signed(SSL_CTX *ctx) {
    int rc = -1;
    EVP_PKEY *pkey = NULL;
    X509 *x = NULL;
    char host[256] = "packetwyrm-proxyd";

    if (gethostname(host, sizeof(host) - 1) != 0)
        strcpy(host, "packetwyrm-proxyd");
    host[sizeof(host) - 1] = '\0';

    pkey = EVP_EC_gen("P-256");
    if (!pkey) goto out;

    x = X509_new();
    if (!x) goto out;
    ASN1_INTEGER_set(X509_get_serialNumber(x), 1);
    X509_gmtime_adj(X509_getm_notBefore(x), 0);
    X509_gmtime_adj(X509_getm_notAfter(x), 60L * 60 * 24 * 3650); /* ~10y */
    if (X509_set_pubkey(x, pkey) != 1) goto out;

    X509_NAME *name = X509_get_subject_name(x);
    X509_NAME_add_entry_by_txt(name, "CN", MBSTRING_ASC,
                               (unsigned char *)host, -1, -1, 0);
    X509_NAME_add_entry_by_txt(name, "O", MBSTRING_ASC,
                               (unsigned char *)"PacketWyrm", -1, -1, 0);
    if (X509_set_issuer_name(x, name) != 1) goto out; /* self-issued */
    if (X509_sign(x, pkey, EVP_sha256()) == 0) goto out;

    if (SSL_CTX_use_certificate(ctx, x) != 1) goto out;
    if (SSL_CTX_use_PrivateKey(ctx, pkey) != 1) goto out;

    fputs("  TLS: using auto-generated self-signed certificate\n", stdout);
    print_fingerprint(x);
    rc = 0;
out:
    if (rc != 0) ERR_print_errors_fp(stderr);
    X509_free(x);
    EVP_PKEY_free(pkey);
    return rc;
}

static SSL_CTX *tls_ctx_new(const struct proxyd_opts *o) {
    SSL_CTX *ctx = SSL_CTX_new(TLS_server_method());
    if (!ctx) { ERR_print_errors_fp(stderr); return NULL; }
    SSL_CTX_set_min_proto_version(ctx, TLS1_2_VERSION);

    if (o->tls_cert && o->tls_key) {
        if (SSL_CTX_use_certificate_chain_file(ctx, o->tls_cert) != 1 ||
            SSL_CTX_use_PrivateKey_file(ctx, o->tls_key, SSL_FILETYPE_PEM) != 1 ||
            SSL_CTX_check_private_key(ctx) != 1) {
            fprintf(stderr, "proxyd: failed to load cert/key\n");
            ERR_print_errors_fp(stderr);
            SSL_CTX_free(ctx);
            return NULL;
        }
        printf("  TLS: using %s / %s\n", o->tls_cert, o->tls_key);
    } else if (tls_self_signed(ctx) != 0) {
        SSL_CTX_free(ctx);
        return NULL;
    }
    return ctx;
}

/* ------------------------------------------------------------------ */
/* HTTP I/O helpers (work over either an SSL* or a raw fd)            */
/* ------------------------------------------------------------------ */

struct conn {
    int   fd;
    SSL  *ssl;   /* NULL when --no-tls */
};

static ssize_t conn_read(struct conn *c, void *buf, size_t n) {
    if (c->ssl) return SSL_read(c->ssl, buf, (int)n);
    return read(c->fd, buf, n);
}

static int conn_write_all(struct conn *c, const void *buf, size_t n) {
    const char *p = buf;
    while (n > 0) {
        ssize_t w = c->ssl ? SSL_write(c->ssl, p, (int)n) : write(c->fd, p, n);
        if (w <= 0) return -1;
        p += w;
        n -= (size_t)w;
    }
    return 0;
}

static void http_reply(struct conn *c, int code, const char *status,
                       const char *ctype, const void *body, size_t blen) {
    char hdr[1024];
    int hn = snprintf(hdr, sizeof(hdr),
                      "HTTP/1.1 %d %s\r\n"
                      "Content-Type: %s\r\n"
                      "Content-Length: %zu\r\n"
                      "Content-Security-Policy: %s\r\n"
                      "X-Content-Type-Options: nosniff\r\n"
                      "Cache-Control: no-store\r\n"
                      "Connection: close\r\n\r\n",
                      code, status, ctype, blen, PROXYD_CSP);
    /* snprintf truncates silently once the buffer fills; sending a truncated
     * header (no terminating CRLFCRLF) would desync the response. Treat an
     * over-long header as an error and drop the connection instead. */
    if (hn <= 0 || hn >= (int)sizeof(hdr)) return;
    if (conn_write_all(c, hdr, (size_t)hn) != 0) return;
    if (blen) conn_write_all(c, body, blen);
}

static void http_error(struct conn *c, int code, const char *status) {
    char body[128];
    int n = snprintf(body, sizeof(body), "{\"error\":\"%s\"}", status);
    http_reply(c, code, status, "application/json", body, (size_t)n);
}

/* Serve a static asset by EXACT table lookup. Strips any query string; "/" maps
 * to "/index.html". Because the match is exact against the embedded blob table
 * (no filesystem access), path traversal is structurally impossible: an encoded
 * or "../" path simply fails to match and 404s. Returns 1 if served, else 0. */
static int serve_asset(struct conn *c, const char *path) {
    char clean[256];
    size_t i = 0;
    for (; path[i] && path[i] != '?' && i + 1 < sizeof(clean); i++) clean[i] = path[i];
    clean[i] = '\0';
    const char *lookup = (clean[0] == '\0' || strcmp(clean, "/") == 0)
                             ? "/index.html" : clean;
    for (size_t k = 0; k < pw_assets_n; k++) {
        if (strcmp(pw_assets[k].path, lookup) == 0) {
            http_reply(c, 200, "OK", pw_assets[k].ctype,
                       pw_assets[k].data, pw_assets[k].len);
            return 1;
        }
    }
    return 0;
}

/* ------------------------------------------------------------------ */
/* RPC relay to the daemon                                            */
/* ------------------------------------------------------------------ */

static int daemon_relay(const char *body, size_t blen,
                        char *resp, size_t rcap, size_t *rlen) {
    int fd = -1;
    if (pw_ipc_connect(g_daemon_sock, &fd) != PW_OK) return -1;
    /* Bound the relay: the daemon is single-threaded, so a busy/wedged daemon
     * must not pin this worker (and eventually all PROXYD_MAX_THREADS) forever.
     * 10 s is generous for a control RPC over a local socket. */
    struct timeval tv = { .tv_sec = 10, .tv_usec = 0 };
    setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof tv);
    setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof tv);
    int rc = -1;
    if (pw_ipc_write_frame(fd, body, blen) == PW_OK &&
        pw_ipc_read_frame(fd, resp, rcap, rlen) == PW_OK)
        rc = 0;
    close(fd);
    return rc;
}

/* ------------------------------------------------------------------ */
/* Per-connection handler                                             */
/* ------------------------------------------------------------------ */

/* Seconds of CLOCK_MONOTONIC elapsed since *t0 (sub-second part ignored;
 * accurate enough for whole-request deadlines). */
static long mono_elapsed_s(const struct timespec *t0) {
    struct timespec now;
    clock_gettime(CLOCK_MONOTONIC, &now);
    return (long)(now.tv_sec - t0->tv_sec);
}

/* Read the full HTTP request (headers + Content-Length body) into buf.
 * Returns total bytes, -1 on error, or -2 when the whole-request deadline
 * (PROXYD_REQ_DEADLINE_S) expires. Sets *body_off / *body_len.
 *
 * SO_RCVTIMEO bounds each individual read; the deadline check between reads
 * bounds the request as a whole so a client trickling bytes can't pin a
 * worker thread indefinitely (Slowloris). */
static ssize_t read_request(struct conn *c, char *buf, size_t cap,
                            size_t *body_off, size_t *body_len) {
    size_t have = 0;
    size_t header_end = 0; /* index just past "\r\n\r\n" */
    struct timespec t0;
    clock_gettime(CLOCK_MONOTONIC, &t0);

    /* Read until we have the full header block. */
    while (header_end == 0) {
        if (have >= cap) return -1;
        ssize_t r = conn_read(c, buf + have, cap - have);
        if (r <= 0) return -1;
        if (mono_elapsed_s(&t0) >= PROXYD_REQ_DEADLINE_S) return -2;
        have += (size_t)r;
        /* search for CRLFCRLF (only need to scan the fresh tail + 3) */
        for (size_t i = (have >= (size_t)r + 3 ? have - (size_t)r - 3 : 0);
             i + 3 < have; i++) {
            if (buf[i] == '\r' && buf[i + 1] == '\n' &&
                buf[i + 2] == '\r' && buf[i + 3] == '\n') {
                header_end = i + 4;
                break;
            }
        }
    }

    /* Parse Content-Length, strictly: only at a header-LINE start (not anywhere
     * in the block), a purely-numeric value (digits then CR/LF), reject overflow
     * and a DUPLICATE Content-Length (a conflicting/second value is a classic
     * request-smuggling vector behind a reverse proxy). */
    size_t clen = 0;
    int seen_cl = 0;
    size_t line_start = 0;
    for (size_t i = 0; i < header_end; i++) {
        if (buf[i] == '\n') { line_start = i + 1; continue; }
        if (i != line_start) continue;
        if ((size_t)(header_end - i) <= 15 ||
            strncasecmp(buf + i, "Content-Length:", 15) != 0) continue;
        if (seen_cl) return -1;                 /* duplicate Content-Length */
        seen_cl = 1;
        const char *p = buf + i + 15;
        while (*p == ' ' || *p == '\t') p++;
        if (*p < '0' || *p > '9') return -1;    /* must have at least one digit */
        errno = 0;
        char *end = NULL;
        unsigned long long v = strtoull(p, &end, 10);
        while (*end == ' ' || *end == '\t') end++;
        if (*end != '\r' && *end != '\n') return -1;   /* trailing junk */
        if (errno == ERANGE) return -1;                /* overflow */
        clen = (size_t)v;
    }
    if (clen > PW_IPC_FRAME_MAX) return -1;
    if (header_end + clen > cap) return -1;

    /* Read the remaining body bytes. */
    while (have < header_end + clen) {
        ssize_t r = conn_read(c, buf + have, cap - have);
        if (r <= 0) return -1;
        if (mono_elapsed_s(&t0) >= PROXYD_REQ_DEADLINE_S) return -2;
        have += (size_t)r;
    }

    *body_off = header_end;
    *body_len = clen;
    return (ssize_t)have;
}

/* Extract the value of HTTP header `name` (must include the trailing ':',
 * e.g. "Host:") from the header block buf[0..hdr_end). Case-insensitive
 * name match at line start; value is whitespace-trimmed and NUL-terminated
 * into out. Returns 0 when found, -1 otherwise. */
static int find_header(const char *buf, size_t hdr_end, const char *name,
                       char *out, size_t outcap) {
    size_t nlen = strlen(name);
    for (size_t i = 0; i + nlen < hdr_end; i++) {
        if (i > 0 && buf[i - 1] != '\n') continue;   /* line starts only */
        if (strncasecmp(buf + i, name, nlen) != 0) continue;
        size_t v = i + nlen;
        while (v < hdr_end && (buf[v] == ' ' || buf[v] == '\t')) v++;
        size_t e = v;
        while (e < hdr_end && buf[e] != '\r' && buf[e] != '\n') e++;
        while (e > v && (buf[e - 1] == ' ' || buf[e - 1] == '\t')) e--;
        if (e - v >= outcap) return -1;
        memcpy(out, buf + v, e - v);
        out[e - v] = '\0';
        return 0;
    }
    return -1;
}

/* One Host candidate vs one allowed name; an IPv6 bracket literal also
 * matches its unbracketed form ("[::1]" == "::1"). */
static bool host_matches(const char *host, const char *want) {
    if (strcasecmp(host, want) == 0) return true;
    size_t hl = strlen(host);
    if (hl >= 2 && host[0] == '[' && host[hl - 1] == ']' &&
        strlen(want) == hl - 2 && strncasecmp(host + 1, want, hl - 2) == 0)
        return true;
    return false;
}

/* Host-header allow-list check for /api/rpc (anti DNS-rebinding: a page on
 * attacker.example that rebinds its name to us would send
 * "Host: attacker.example", which no allowed name matches). Accepts
 * loopback names, the bound address, and any --allowed-host entries;
 * an optional ":port" suffix is ignored. */
static bool host_allowed(const char *raw) {
    char host[300];
    snprintf(host, sizeof(host), "%s", raw);

    /* Strip the port: "[v6]:port" after the bracket, "name:port"/"v4:port"
     * at the single colon. A bare-IPv6 Host (multiple colons, no brackets)
     * is left untouched. */
    if (host[0] == '[') {
        char *rb = strchr(host, ']');
        if (rb && rb[1] == ':') rb[1] = '\0';
    } else {
        char *colon = strchr(host, ':');
        if (colon && strchr(colon + 1, ':') == NULL) *colon = '\0';
    }
    if (host[0] == '\0') return false;

    static const char *builtin[] = { "localhost", "127.0.0.1", "::1" };
    for (size_t i = 0; i < sizeof(builtin) / sizeof(builtin[0]); i++)
        if (host_matches(host, builtin[i])) return true;
    if (g_listen_addr && host_matches(host, g_listen_addr)) return true;
    if (g_allowed_hosts)
        for (char **p = g_allowed_hosts; *p; p++)
            if (host_matches(host, *p)) return true;
    return false;
}

static int probe_daemon_secret(void); /* defined below (startup safeguard) */

/* Non-loopback binds only relay while the daemon is KNOWN to require a
 * secret. The startup probe alone is TOCTOU: a daemon restarted later
 * without a secret would be exposed through an already-running public
 * proxyd. Re-confirm lazily, at most every PROXYD_PROBE_PERIOD_S; fail
 * CLOSED on a failed/unreachable probe (matching the startup policy) and
 * re-probe on the next request so recovery is immediate. Loopback binds
 * and --insecure-no-auth are exempt, matching startup. */
static bool auth_probe_current(void) {
    if (!g_probe_enforce) return true;
    bool ok = false;
    pthread_mutex_lock(&g_probe_mu);   /* also serialises concurrent probes */
    struct timespec now;
    clock_gettime(CLOCK_MONOTONIC, &now);
    if (g_probe_ok_valid &&
        now.tv_sec - g_probe_ok_ts.tv_sec < PROXYD_PROBE_PERIOD_S) {
        ok = true;
    } else if (probe_daemon_secret() == 1) {
        g_probe_ok_ts = now;
        g_probe_ok_valid = true;
        ok = true;
    } else {
        g_probe_ok_valid = false;
    }
    pthread_mutex_unlock(&g_probe_mu);
    return ok;
}

static void serve(struct conn *c) {
    /* +1 so we can always NUL-terminate: the parse below treats buf as a C
     * string (sscanf "%s"), and without a terminator a request with no
     * whitespace/NUL in the received bytes would read past the buffer. */
    char *buf = malloc(PROXYD_REQ_MAX + 1);
    if (!buf) { http_error(c, 500, "out of memory"); return; }

    size_t body_off = 0, body_len = 0;
    ssize_t total = read_request(c, buf, PROXYD_REQ_MAX, &body_off, &body_len);
    if (total == -2) { http_error(c, 408, "request timeout"); free(buf); return; }
    if (total < 0) { free(buf); return; }
    buf[total] = '\0';   /* bound the string parse below (total <= PROXYD_REQ_MAX) */

    /* Parse the request line: "METHOD SP PATH SP VERSION". */
    char method[8] = {0}, path[256] = {0};
    if (sscanf(buf, "%7s %255s", method, path) != 2) {
        http_error(c, 400, "bad request");
        free(buf);
        return;
    }

    if (strcmp(method, "POST") == 0 && strcmp(path, "/api/rpc") == 0) {
        /* CSRF defence for the sanctioned loopback + secretless-daemon
         * deployment (and defence-in-depth elsewhere), two halves:
         *  - X-PW-Request: a custom header makes a genuinely cross-origin
         *    browser POST trigger a CORS preflight, and we never answer
         *    OPTIONS, so it fails. (Header-free "simple" POSTs from any web
         *    page would otherwise reach us without any preflight.)
         *  - Host allow-list: DNS rebinding makes the attacker's page
         *    SAME-origin, so custom headers alone don't help -- but the
         *    rebound request carries the attacker's name in Host. */
        char hv[300];
        if (find_header(buf, body_off, "X-PW-Request:", hv, sizeof(hv)) != 0 ||
            strcmp(hv, "1") != 0) {
            http_error(c, 403, "missing X-PW-Request header");
        } else if (find_header(buf, body_off, "Host:", hv, sizeof(hv)) != 0 ||
                   !host_allowed(hv)) {
            http_error(c, 403, "host not allowed");
        } else if (!auth_probe_current()) {
            http_error(c, 403, "daemon auth not confirmed");
        } else {
            /* Per-connection response buffer: workers must NOT share it. */
            char *resp = malloc(PW_IPC_FRAME_MAX);
            size_t rlen = 0;
            if (!resp) {
                http_error(c, 500, "out of memory");
            } else if (body_len == 0) {
                http_error(c, 400, "empty body");
            } else if (daemon_relay(buf + body_off, body_len,
                                    resp, PW_IPC_FRAME_MAX, &rlen) == 0) {
                http_reply(c, 200, "OK", "application/json", resp, rlen);
            } else {
                http_error(c, 502, "daemon unreachable");
            }
            free(resp);
        }
    } else if (strcmp(method, "GET") == 0 && strcmp(path, "/proxyd/version") == 0) {
        char b[128];
        int n = snprintf(b, sizeof b, "{\"version\":\"%s\"}", pw_version_string());
        http_reply(c, 200, "OK", "application/json", b, (size_t)n);
    } else if (strcmp(method, "GET") == 0 && serve_asset(c, path)) {
        /* served a static asset from the embedded table */
    } else {
        http_error(c, 404, "not found");
    }

    free(buf);
}

static void *worker(void *arg) {
    int cfd = (int)(intptr_t)arg;
    struct conn c = { .fd = cfd, .ssl = NULL };

    /* Network-facing gateway with a bounded thread pool: don't let a slow or
     * stuck client hold a worker (and eventually all PROXYD_MAX_THREADS) open.
     * A read/write that stalls past the timeout fails the connection; if the
     * timeout can't even be armed, drop the connection rather than serve it
     * unbounded (matches the daemon's set_conn_timeout). */
    struct timeval tv = { .tv_sec = 15, .tv_usec = 0 };
    if (setsockopt(cfd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof tv) != 0 ||
        setsockopt(cfd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof tv) != 0) {
        close(cfd);
        atomic_fetch_sub(&g_active_threads, 1);
        return NULL;
    }

    if (g_ssl_ctx) {
        c.ssl = SSL_new(g_ssl_ctx);
        if (c.ssl) {
            SSL_set_fd(c.ssl, cfd);
            if (SSL_accept(c.ssl) == 1)
                serve(&c);
            SSL_shutdown(c.ssl);
            SSL_free(c.ssl);
        }
    } else {
        serve(&c);
    }

    close(cfd);
    atomic_fetch_sub(&g_active_threads, 1);
    return NULL;
}

/* ------------------------------------------------------------------ */
/* Startup auth safeguard                                             */
/* ------------------------------------------------------------------ */

/* Probe the daemon with an unauthenticated `version` request. Returns:
 *   1  -> daemon requires a secret (got "unauthorized")  [safe]
 *   0  -> daemon has NO secret configured (open)          [risky]
 *  -1  -> could not reach the daemon                      [unknown] */
static int probe_daemon_secret(void) {
    char resp[PW_IPC_FRAME_MAX];
    size_t rlen = 0;
    const char *req = "{\"rpc\":\"version\"}";
    if (daemon_relay(req, strlen(req), resp, sizeof(resp) - 1, &rlen) != 0)
        return -1;
    resp[rlen < sizeof(resp) ? rlen : sizeof(resp) - 1] = '\0';
    return (strstr(resp, "unauthorized") != NULL) ? 1 : 0;
}

/* ------------------------------------------------------------------ */
/* main                                                               */
/* ------------------------------------------------------------------ */

static void usage(void) {
    fputs(
        "usage: packetwyrm-proxyd [options]\n"
        "  -c, --config FILE    read options from a config file (key: value;\n"
        "                       keys: listen, socket, tls_cert, tls_key, no_tls,\n"
        "                       insecure_no_auth, allowed_hosts). CLI flags below\n"
        "                       override the file.\n"
        "  --listen ADDR:PORT   bind address (default " PROXYD_DEFAULT_LISTEN ")\n"
        "  --socket PATH        daemon control socket (default "
            PW_IPC_DEFAULT_PATH ")\n"
        "  --tls-cert FILE      TLS certificate (PEM); default self-signed\n"
        "  --tls-key FILE       TLS private key (PEM)\n"
        "  --no-tls             serve plain HTTP (localhost / SSH tunnel only)\n"
        "  --insecure-no-auth   allow non-loopback bind even if the daemon\n"
        "                       has no secret configured\n"
        "  --allowed-host NAME[,NAME...]\n"
        "                       additional Host header values accepted on\n"
        "                       POST /api/rpc (anti DNS-rebinding; localhost,\n"
        "                       127.0.0.1, [::1] and the --listen address are\n"
        "                       always accepted)\n"
        "  -h, --help           this help\n",
        stderr);
}

/* Strict decimal port parse: reject empty, trailing junk (e.g. "8443abc"),
 * overflow, and out-of-range -- atoi() silently accepted all of those. */
static int parse_port_strict(const char *s, int *out) {
    if (!s || !*s) return -1;
    char *e = NULL;
    errno = 0;
    long v = strtol(s, &e, 10);
    if (errno != 0 || *e != '\0' || v <= 0 || v > 65535) return -1;
    *out = (int)v;
    return 0;
}

static int parse_listen(struct proxyd_opts *o, const char *s) {
    /* ADDR:PORT or just PORT. */
    const char *colon = strrchr(s, ':');
    static char abuf[128];
    if (colon) {
        size_t alen = (size_t)(colon - s);
        if (alen >= sizeof(abuf)) return -1;
        memcpy(abuf, s, alen);
        abuf[alen] = '\0';
        o->listen_addr = abuf;
        return parse_port_strict(colon + 1, &o->listen_port);
    }
    return parse_port_strict(s, &o->listen_port);
}

/* Parse a boolean scalar: true/false, yes/no, on/off, 1/0 (case-insensitive).
 * Returns 0 and sets *out on success, -1 on an unrecognized value. */
static int parse_bool(const char *s, bool *out) {
    if (!strcasecmp(s, "true") || !strcasecmp(s, "yes") ||
        !strcasecmp(s, "on")   || !strcmp(s, "1"))  { *out = true;  return 0; }
    if (!strcasecmp(s, "false")|| !strcasecmp(s, "no") ||
        !strcasecmp(s, "off")  || !strcmp(s, "0"))  { *out = false; return 0; }
    return -1;
}

/* Load proxyd options from a small YAML-subset config file: one `key: value`
 * per line, `#` comments and blank lines ignored, optional surrounding quotes
 * on values. Recognized keys mirror the CLI flags:
 *   listen, socket, tls_cert, tls_key, no_tls, insecure_no_auth, allowed_hosts
 * Values seed `o`; explicit CLI flags parsed afterwards override them. String
 * values are strdup'd (config is loaded once at startup). Returns 0 on success,
 * -1 on a read/parse error (with a message on stderr). */
static int load_config_file(struct proxyd_opts *o, const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) { fprintf(stderr, "proxyd: cannot open config %s: %s\n", path, strerror(errno)); return -1; }
    char line[1024];
    int lineno = 0, rc = 0;
    while (fgets(line, sizeof line, f)) {
        lineno++;
        char *p = line;
        while (*p == ' ' || *p == '\t') p++;          /* leading ws */
        if (*p == '#' || *p == '\n' || *p == '\0' || *p == '\r') continue;
        char *colon = strchr(p, ':');
        if (!colon) { fprintf(stderr, "proxyd: %s:%d: expected 'key: value'\n", path, lineno); rc = -1; break; }
        *colon = '\0';
        char *key = p;
        /* trim trailing ws off key */
        char *ke = key + strlen(key);
        while (ke > key && (ke[-1] == ' ' || ke[-1] == '\t')) *--ke = '\0';
        char *val = colon + 1;
        while (*val == ' ' || *val == '\t') val++;    /* leading ws off value */
        /* strip trailing ws / newline */
        char *ve = val + strlen(val);
        while (ve > val && (ve[-1] == '\n' || ve[-1] == '\r' || ve[-1] == ' ' || ve[-1] == '\t')) *--ve = '\0';
        /* strip a single pair of surrounding quotes */
        size_t vl = strlen(val);
        if (vl >= 2 && ((val[0] == '"' && val[vl-1] == '"') || (val[0] == '\'' && val[vl-1] == '\''))) {
            val[vl-1] = '\0'; val++;
        }

        if (!strcmp(key, "listen")) {
            if (parse_listen(o, val) != 0) { fprintf(stderr, "proxyd: %s:%d: bad listen '%s'\n", path, lineno, val); rc = -1; break; }
        } else if (!strcmp(key, "socket")) {
            o->daemon_sock = strdup(val);
        } else if (!strcmp(key, "tls_cert")) {
            o->tls_cert = val[0] ? strdup(val) : NULL;
        } else if (!strcmp(key, "tls_key")) {
            o->tls_key = val[0] ? strdup(val) : NULL;
        } else if (!strcmp(key, "allowed_hosts") || !strcmp(key, "allowed_host")) {
            o->allowed_hosts = strdup(val);
        } else if (!strcmp(key, "no_tls")) {
            if (parse_bool(val, &o->no_tls) != 0) { fprintf(stderr, "proxyd: %s:%d: bad bool '%s'\n", path, lineno, val); rc = -1; break; }
        } else if (!strcmp(key, "insecure_no_auth")) {
            if (parse_bool(val, &o->insecure_no_auth) != 0) { fprintf(stderr, "proxyd: %s:%d: bad bool '%s'\n", path, lineno, val); rc = -1; break; }
        } else {
            fprintf(stderr, "proxyd: %s:%d: unknown key '%s'\n", path, lineno, key); rc = -1; break;
        }
    }
    fclose(f);
    return rc;
}

int main(int argc, char **argv) {
    struct proxyd_opts o = {
        .listen_addr = "0.0.0.0",
        .listen_port = PROXYD_DEFAULT_PORT,
        .daemon_sock = PW_IPC_DEFAULT_PATH,
    };

    /* First pass: if a config file is named, load it so its values seed `o`
     * before the CLI loop below, which then OVERRIDES them (CLI > file). */
    for (int i = 1; i < argc; i++) {
        if ((!strcmp(argv[i], "--config") || !strcmp(argv[i], "-c")) && i + 1 < argc) {
            if (load_config_file(&o, argv[i + 1]) != 0) return 2;
        }
    }

    for (int i = 1; i < argc; i++) {
        const char *a = argv[i];
        if ((!strcmp(a, "--config") || !strcmp(a, "-c")) && i + 1 < argc) {
            i++;   /* consumed in the first pass */
        } else if (!strcmp(a, "--listen") && i + 1 < argc) {
            if (parse_listen(&o, argv[++i]) != 0) {
                fprintf(stderr, "proxyd: bad --listen\n");
                return 2;
            }
        } else if (!strcmp(a, "--socket") && i + 1 < argc) {
            o.daemon_sock = argv[++i];
        } else if (!strcmp(a, "--tls-cert") && i + 1 < argc) {
            o.tls_cert = argv[++i];
        } else if (!strcmp(a, "--tls-key") && i + 1 < argc) {
            o.tls_key = argv[++i];
        } else if (!strcmp(a, "--no-tls")) {
            o.no_tls = true;
        } else if (!strcmp(a, "--insecure-no-auth")) {
            o.insecure_no_auth = true;
        } else if (!strcmp(a, "--allowed-host") && i + 1 < argc) {
            o.allowed_hosts = argv[++i];
        } else if (!strcmp(a, "-h") || !strcmp(a, "--help")) {
            usage();
            return 0;
        } else {
            fprintf(stderr, "proxyd: unknown arg '%s'\n", a);
            usage();
            return 2;
        }
    }
    if ((o.tls_cert && !o.tls_key) || (!o.tls_cert && o.tls_key)) {
        fprintf(stderr, "proxyd: --tls-cert and --tls-key must be paired\n");
        return 2;
    }

    signal(SIGPIPE, SIG_IGN);
    g_daemon_sock = o.daemon_sock;

    /* Split --allowed-host into a NULL-terminated array (read-only once the
     * worker threads start). */
    if (o.allowed_hosts && o.allowed_hosts[0]) {
        char *dup = strdup(o.allowed_hosts);
        if (!dup) { fprintf(stderr, "proxyd: out of memory\n"); return 1; }
        size_t n = 1;
        for (const char *p = dup; *p; p++) n += (*p == ',');
        g_allowed_hosts = calloc(n + 1, sizeof(*g_allowed_hosts));
        if (!g_allowed_hosts) {
            fprintf(stderr, "proxyd: out of memory\n");
            return 1;
        }
        size_t k = 0;
        for (char *tok = strtok(dup, ","); tok; tok = strtok(NULL, ","))
            if (tok[0]) g_allowed_hosts[k++] = tok;
        g_allowed_hosts[k] = NULL;
    }

    /* Resolve the listen address to a numeric IPv4 up front. We only bind
     * AF_INET, so reject anything inet_pton can't parse (e.g. an IPv6 literal
     * or a hostname) rather than silently falling back to 0.0.0.0 -- that
     * fallback would turn a "loopback-looking" --listen into a public bind. */
    struct in_addr listen_ia;
    if (inet_pton(AF_INET, o.listen_addr, &listen_ia) != 1) {
        fprintf(stderr, "proxyd: --listen address must be a numeric IPv4 "
                        "address (got '%s'); IPv6/hostnames are not supported\n",
                o.listen_addr);
        return 2;
    }
    bool loopback = (ntohl(listen_ia.s_addr) >> 24) == 127; /* 127.0.0.0/8 */
    g_listen_addr = o.listen_addr;

    printf("packetwyrm-proxyd starting\n");
    printf("  daemon socket: %s\n", o.daemon_sock);

    /* Auth safeguard: on a non-loopback bind, only proceed if the daemon is
     * KNOWN to require a secret (sec == 1). If it has none (sec == 0) or we
     * can't tell because it's unreachable at startup (sec == -1), fail CLOSED
     * -- otherwise a no-secret daemon coming up later would be exposed. */
    int sec = probe_daemon_secret();
    if (!loopback && !o.insecure_no_auth && sec != 1) {
        fprintf(stderr,
            "proxyd: REFUSING to bind %s:%d -- %s, so a public bind could "
            "expose full control.\n"
            "        Set system.secret in the daemon env config, bind "
            "127.0.0.1, or pass --insecure-no-auth to override.\n",
            o.listen_addr, o.listen_port,
            sec == 0 ? "the daemon has no secret configured"
                     : "the daemon is unreachable so its auth can't be confirmed");
        return 1;
    }
    if (sec == -1)
        fprintf(stderr, "  warning: daemon not reachable at startup "
                        "(will relay once it is up)\n");
    else
        printf("  daemon auth: %s\n", sec == 1 ? "secret required" : "OPEN (no secret)");

    /* Second safeguard: --no-tls on a non-loopback bind sends the access secret
     * (in the JSON body) across the network in PLAINTEXT even when the daemon
     * requires one. --no-tls is meant for localhost / an SSH tunnel; refuse a
     * public plaintext bind unless the operator explicitly overrides. */
    if (!loopback && o.no_tls && !o.insecure_no_auth) {
        fprintf(stderr,
            "proxyd: REFUSING to bind %s:%d with --no-tls -- the access secret "
            "would cross the network in plaintext.\n"
            "        Use TLS (drop --no-tls), bind 127.0.0.1 (localhost / SSH "
            "tunnel), or pass --insecure-no-auth to override.\n",
            o.listen_addr, o.listen_port);
        return 1;
    }

    /* Arm the lazy re-probe (see auth_probe_current). Reaching this point
     * non-loopback without the override means the startup probe passed;
     * seed the freshness window from it. */
    g_probe_enforce = !loopback && !o.insecure_no_auth;
    if (g_probe_enforce && sec == 1) {
        clock_gettime(CLOCK_MONOTONIC, &g_probe_ok_ts);
        g_probe_ok_valid = true;
    }

    /* TLS. */
    if (!o.no_tls) {
        g_ssl_ctx = tls_ctx_new(&o);
        if (!g_ssl_ctx) return 1;
    } else {
        printf("  TLS: DISABLED (--no-tls, plaintext)\n");
    }

    /* Listen socket. On a bind/listen failure, close the socket and free the
     * TLS context before exiting (tidy even though the process is ending). */
    int lfd = socket(AF_INET, SOCK_STREAM | SOCK_CLOEXEC, 0);
    if (lfd < 0) { perror("socket"); if (g_ssl_ctx) SSL_CTX_free(g_ssl_ctx); return 1; }
    int one = 1;
    setsockopt(lfd, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));
    struct sockaddr_in sa = { .sin_family = AF_INET,
                              .sin_port = htons((uint16_t)o.listen_port),
                              .sin_addr = listen_ia };
    if (bind(lfd, (struct sockaddr *)&sa, sizeof(sa)) < 0) {
        perror("bind");
        close(lfd); if (g_ssl_ctx) SSL_CTX_free(g_ssl_ctx);
        return 1;
    }
    if (listen(lfd, 16) < 0) {
        perror("listen");
        close(lfd); if (g_ssl_ctx) SSL_CTX_free(g_ssl_ctx);
        return 1;
    }
    printf("  listening on %s://%s:%d/\n", o.no_tls ? "http" : "https",
           o.listen_addr, o.listen_port);
    fflush(stdout);

    for (;;) {
        int cfd = accept(lfd, NULL, NULL);
        if (cfd < 0) {
            if (errno == EINTR) continue;
            perror("accept");
            break;
        }
        if (atomic_load(&g_active_threads) >= PROXYD_MAX_THREADS) {
            struct conn c = { .fd = cfd, .ssl = NULL };
            /* Can't cheaply TLS-negotiate here; just drop over plaintext. */
            if (!g_ssl_ctx) http_error(&c, 503, "too many connections");
            close(cfd);
            continue;
        }
        atomic_fetch_add(&g_active_threads, 1);
        pthread_t th;
        if (pthread_create(&th, NULL, worker, (void *)(intptr_t)cfd) != 0) {
            atomic_fetch_sub(&g_active_threads, 1);
            close(cfd);
            continue;
        }
        pthread_detach(th);
    }

    close(lfd);
    if (g_ssl_ctx) SSL_CTX_free(g_ssl_ctx);
    return 0;
}
