/* packetwyrm-proxyd: TLS-terminating HTTPS gateway for the PacketWyrm Web GUI
 * and remote CLI.
 *
 * This is a *stateless relay*, deliberately separate from packetwyrmd:
 *   [browser / pktwyrm --host] --HTTPS--> [packetwyrm-proxyd]
 *                                              |
 *                                     Unix socket (4B len + JSON)
 *                                              v
 *                                        [packetwyrmd]
 *
 * It serves the embedded single-page GUI (GET /) and forwards
 * `POST /api/rpc` request bodies verbatim onto the daemon's control
 * socket, returning the daemon's JSON reply. It does NOT parse or
 * understand the RPC payload and holds no shared state with the daemon,
 * so it cannot stall the daemon's single-threaded control/servo loop.
 *
 * Authentication is unchanged: the daemon remains the sole authority.
 * The client puts its `"secret"` in the JSON body; we forward it as-is;
 * the daemon does the constant-time compare. This gateway needs no
 * knowledge of the secret. See docs/design/web-gui.md.
 */
#include <arpa/inet.h>
#include <errno.h>
#include <netinet/in.h>
#include <pthread.h>
#include <signal.h>
#include <stdatomic.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <unistd.h>

#include <openssl/err.h>
#include <openssl/evp.h>
#include <openssl/pem.h>
#include <openssl/ssl.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>

#include "packetwyrm/ipc.h"
#include "packetwyrm/packetwyrm.h"

/* Embedded GUI asset (generated by `xxd -i index.html` in the Makefile). */
#include "proxyd_assets.h"

#define PROXYD_DEFAULT_LISTEN "0.0.0.0:8443"
#define PROXYD_DEFAULT_PORT   8443
#define PROXYD_MAX_THREADS     32
#define PROXYD_REQ_MAX         (PW_IPC_FRAME_MAX + 8192) /* headers + body */

struct proxyd_opts {
    const char *listen_addr;   /* IPv4 dotted address to bind */
    int         listen_port;
    const char *daemon_sock;
    const char *tls_cert;      /* NULL -> auto self-signed */
    const char *tls_key;
    bool        no_tls;        /* plaintext HTTP (localhost / SSH tunnel) */
    bool        insecure_no_auth;
};

/* Shared, read-only after startup: safe to touch from worker threads. */
static SSL_CTX          *g_ssl_ctx;      /* NULL when --no-tls */
static const char       *g_daemon_sock;
static _Atomic int       g_active_threads;

/* ------------------------------------------------------------------ */
/* TLS setup                                                          */
/* ------------------------------------------------------------------ */

static void print_fingerprint(X509 *x) {
    unsigned char md[EVP_MAX_MD_SIZE];
    unsigned int n = 0;
    if (X509_digest(x, EVP_sha256(), md, &n) != 1) return;
    fputs("  TLS cert SHA-256: ", stdout);
    for (unsigned i = 0; i < n; i++)
        printf("%02X%s", md[i], (i + 1 < n) ? ":" : "");
    putchar('\n');
}

/* Generate an in-memory self-signed EC (P-256) certificate and load it
 * into `ctx`. Browsers will warn (self-signed); the printed fingerprint
 * lets an operator verify. */
static int tls_self_signed(SSL_CTX *ctx) {
    int rc = -1;
    EVP_PKEY *pkey = NULL;
    X509 *x = NULL;
    char host[256] = "packetwyrm-proxyd";

    if (gethostname(host, sizeof(host) - 1) != 0)
        strcpy(host, "packetwyrm-proxyd");
    host[sizeof(host) - 1] = '\0';

    pkey = EVP_EC_gen("P-256");
    if (!pkey) goto out;

    x = X509_new();
    if (!x) goto out;
    ASN1_INTEGER_set(X509_get_serialNumber(x), 1);
    X509_gmtime_adj(X509_getm_notBefore(x), 0);
    X509_gmtime_adj(X509_getm_notAfter(x), 60L * 60 * 24 * 3650); /* ~10y */
    if (X509_set_pubkey(x, pkey) != 1) goto out;

    X509_NAME *name = X509_get_subject_name(x);
    X509_NAME_add_entry_by_txt(name, "CN", MBSTRING_ASC,
                               (unsigned char *)host, -1, -1, 0);
    X509_NAME_add_entry_by_txt(name, "O", MBSTRING_ASC,
                               (unsigned char *)"PacketWyrm", -1, -1, 0);
    if (X509_set_issuer_name(x, name) != 1) goto out; /* self-issued */
    if (X509_sign(x, pkey, EVP_sha256()) == 0) goto out;

    if (SSL_CTX_use_certificate(ctx, x) != 1) goto out;
    if (SSL_CTX_use_PrivateKey(ctx, pkey) != 1) goto out;

    fputs("  TLS: using auto-generated self-signed certificate\n", stdout);
    print_fingerprint(x);
    rc = 0;
out:
    if (rc != 0) ERR_print_errors_fp(stderr);
    X509_free(x);
    EVP_PKEY_free(pkey);
    return rc;
}

static SSL_CTX *tls_ctx_new(const struct proxyd_opts *o) {
    SSL_CTX *ctx = SSL_CTX_new(TLS_server_method());
    if (!ctx) { ERR_print_errors_fp(stderr); return NULL; }
    SSL_CTX_set_min_proto_version(ctx, TLS1_2_VERSION);

    if (o->tls_cert && o->tls_key) {
        if (SSL_CTX_use_certificate_chain_file(ctx, o->tls_cert) != 1 ||
            SSL_CTX_use_PrivateKey_file(ctx, o->tls_key, SSL_FILETYPE_PEM) != 1 ||
            SSL_CTX_check_private_key(ctx) != 1) {
            fprintf(stderr, "proxyd: failed to load cert/key\n");
            ERR_print_errors_fp(stderr);
            SSL_CTX_free(ctx);
            return NULL;
        }
        printf("  TLS: using %s / %s\n", o->tls_cert, o->tls_key);
    } else if (tls_self_signed(ctx) != 0) {
        SSL_CTX_free(ctx);
        return NULL;
    }
    return ctx;
}

/* ------------------------------------------------------------------ */
/* HTTP I/O helpers (work over either an SSL* or a raw fd)            */
/* ------------------------------------------------------------------ */

struct conn {
    int   fd;
    SSL  *ssl;   /* NULL when --no-tls */
};

static ssize_t conn_read(struct conn *c, void *buf, size_t n) {
    if (c->ssl) return SSL_read(c->ssl, buf, (int)n);
    return read(c->fd, buf, n);
}

static int conn_write_all(struct conn *c, const void *buf, size_t n) {
    const char *p = buf;
    while (n > 0) {
        ssize_t w = c->ssl ? SSL_write(c->ssl, p, (int)n) : write(c->fd, p, n);
        if (w <= 0) return -1;
        p += w;
        n -= (size_t)w;
    }
    return 0;
}

static void http_reply(struct conn *c, int code, const char *status,
                       const char *ctype, const void *body, size_t blen) {
    char hdr[256];
    int hn = snprintf(hdr, sizeof(hdr),
                      "HTTP/1.1 %d %s\r\n"
                      "Content-Type: %s\r\n"
                      "Content-Length: %zu\r\n"
                      "Cache-Control: no-store\r\n"
                      "Connection: close\r\n\r\n",
                      code, status, ctype, blen);
    if (hn <= 0) return;
    if (conn_write_all(c, hdr, (size_t)hn) != 0) return;
    if (blen) conn_write_all(c, body, blen);
}

static void http_error(struct conn *c, int code, const char *status) {
    char body[128];
    int n = snprintf(body, sizeof(body), "{\"error\":\"%s\"}", status);
    http_reply(c, code, status, "application/json", body, (size_t)n);
}

/* ------------------------------------------------------------------ */
/* RPC relay to the daemon                                            */
/* ------------------------------------------------------------------ */

static int daemon_relay(const char *body, size_t blen,
                        char *resp, size_t rcap, size_t *rlen) {
    int fd = -1;
    if (pw_ipc_connect(g_daemon_sock, &fd) != PW_OK) return -1;
    int rc = -1;
    if (pw_ipc_write_frame(fd, body, blen) == PW_OK &&
        pw_ipc_read_frame(fd, resp, rcap, rlen) == PW_OK)
        rc = 0;
    close(fd);
    return rc;
}

/* ------------------------------------------------------------------ */
/* Per-connection handler                                             */
/* ------------------------------------------------------------------ */

/* Read the full HTTP request (headers + Content-Length body) into buf.
 * Returns total bytes, or -1 on error. Sets *body_off / *body_len. */
static ssize_t read_request(struct conn *c, char *buf, size_t cap,
                            size_t *body_off, size_t *body_len) {
    size_t have = 0;
    size_t header_end = 0; /* index just past "\r\n\r\n" */

    /* Read until we have the full header block. */
    while (header_end == 0) {
        if (have >= cap) return -1;
        ssize_t r = conn_read(c, buf + have, cap - have);
        if (r <= 0) return -1;
        have += (size_t)r;
        /* search for CRLFCRLF (only need to scan the fresh tail + 3) */
        for (size_t i = (have >= (size_t)r + 3 ? have - (size_t)r - 3 : 0);
             i + 3 < have; i++) {
            if (buf[i] == '\r' && buf[i + 1] == '\n' &&
                buf[i + 2] == '\r' && buf[i + 3] == '\n') {
                header_end = i + 4;
                break;
            }
        }
    }

    /* Parse Content-Length (case-insensitive) within the header block. */
    size_t clen = 0;
    for (size_t i = 0; i + 15 < header_end; i++) {
        if (strncasecmp(buf + i, "Content-Length:", 15) == 0) {
            clen = (size_t)strtoul(buf + i + 15, NULL, 10);
            break;
        }
    }
    if (clen > PW_IPC_FRAME_MAX) return -1;
    if (header_end + clen > cap) return -1;

    /* Read the remaining body bytes. */
    while (have < header_end + clen) {
        ssize_t r = conn_read(c, buf + have, cap - have);
        if (r <= 0) return -1;
        have += (size_t)r;
    }

    *body_off = header_end;
    *body_len = clen;
    return (ssize_t)have;
}

static void serve(struct conn *c) {
    char *buf = malloc(PROXYD_REQ_MAX);
    if (!buf) { http_error(c, 500, "out of memory"); return; }

    size_t body_off = 0, body_len = 0;
    ssize_t total = read_request(c, buf, PROXYD_REQ_MAX, &body_off, &body_len);
    if (total < 0) { free(buf); return; }

    /* Parse the request line: "METHOD SP PATH SP VERSION". */
    char method[8] = {0}, path[256] = {0};
    if (sscanf(buf, "%7s %255s", method, path) != 2) {
        http_error(c, 400, "bad request");
        free(buf);
        return;
    }

    if (strcmp(method, "GET") == 0 &&
        (strcmp(path, "/") == 0 || strcmp(path, "/index.html") == 0)) {
        http_reply(c, 200, "OK", "text/html; charset=utf-8",
                   index_html, index_html_len);
    } else if (strcmp(method, "POST") == 0 && strcmp(path, "/api/rpc") == 0) {
        /* Per-connection response buffer: worker threads must NOT share it. */
        char *resp = malloc(PW_IPC_FRAME_MAX);
        size_t rlen = 0;
        if (!resp) {
            http_error(c, 500, "out of memory");
        } else if (body_len == 0) {
            http_error(c, 400, "empty body");
        } else if (daemon_relay(buf + body_off, body_len,
                                resp, PW_IPC_FRAME_MAX, &rlen) == 0) {
            http_reply(c, 200, "OK", "application/json", resp, rlen);
        } else {
            http_error(c, 502, "daemon unreachable");
        }
        free(resp);
    } else if (strcmp(method, "GET") == 0 && strcmp(path, "/proxyd/version") == 0) {
        char b[128];
        int n = snprintf(b, sizeof b, "{\"version\":\"%s\"}", pw_version_string());
        http_reply(c, 200, "OK", "application/json", b, (size_t)n);
    } else {
        http_error(c, 404, "not found");
    }

    free(buf);
}

static void *worker(void *arg) {
    int cfd = (int)(intptr_t)arg;
    struct conn c = { .fd = cfd, .ssl = NULL };

    /* Network-facing gateway with a bounded thread pool: don't let a slow or
     * stuck client hold a worker (and eventually all PROXYD_MAX_THREADS) open.
     * A read/write that stalls past the timeout fails the connection; if the
     * timeout can't even be armed, drop the connection rather than serve it
     * unbounded (matches the daemon's set_conn_timeout). */
    struct timeval tv = { .tv_sec = 15, .tv_usec = 0 };
    if (setsockopt(cfd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof tv) != 0 ||
        setsockopt(cfd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof tv) != 0) {
        close(cfd);
        atomic_fetch_sub(&g_active_threads, 1);
        return NULL;
    }

    if (g_ssl_ctx) {
        c.ssl = SSL_new(g_ssl_ctx);
        if (c.ssl) {
            SSL_set_fd(c.ssl, cfd);
            if (SSL_accept(c.ssl) == 1)
                serve(&c);
            SSL_shutdown(c.ssl);
            SSL_free(c.ssl);
        }
    } else {
        serve(&c);
    }

    close(cfd);
    atomic_fetch_sub(&g_active_threads, 1);
    return NULL;
}

/* ------------------------------------------------------------------ */
/* Startup auth safeguard                                             */
/* ------------------------------------------------------------------ */

/* Probe the daemon with an unauthenticated `version` request. Returns:
 *   1  -> daemon requires a secret (got "unauthorized")  [safe]
 *   0  -> daemon has NO secret configured (open)          [risky]
 *  -1  -> could not reach the daemon                      [unknown] */
static int probe_daemon_secret(void) {
    char resp[PW_IPC_FRAME_MAX];
    size_t rlen = 0;
    const char *req = "{\"rpc\":\"version\"}";
    if (daemon_relay(req, strlen(req), resp, sizeof(resp) - 1, &rlen) != 0)
        return -1;
    resp[rlen < sizeof(resp) ? rlen : sizeof(resp) - 1] = '\0';
    return (strstr(resp, "unauthorized") != NULL) ? 1 : 0;
}

/* ------------------------------------------------------------------ */
/* main                                                               */
/* ------------------------------------------------------------------ */

static void usage(void) {
    fputs(
        "usage: packetwyrm-proxyd [options]\n"
        "  --listen ADDR:PORT   bind address (default " PROXYD_DEFAULT_LISTEN ")\n"
        "  --socket PATH        daemon control socket (default "
            PW_IPC_DEFAULT_PATH ")\n"
        "  --tls-cert FILE      TLS certificate (PEM); default self-signed\n"
        "  --tls-key FILE       TLS private key (PEM)\n"
        "  --no-tls             serve plain HTTP (localhost / SSH tunnel only)\n"
        "  --insecure-no-auth   allow non-loopback bind even if the daemon\n"
        "                       has no secret configured\n"
        "  -h, --help           this help\n",
        stderr);
}

static int parse_listen(struct proxyd_opts *o, const char *s) {
    /* ADDR:PORT or just PORT. */
    const char *colon = strrchr(s, ':');
    static char abuf[128];
    if (colon) {
        size_t alen = (size_t)(colon - s);
        if (alen >= sizeof(abuf)) return -1;
        memcpy(abuf, s, alen);
        abuf[alen] = '\0';
        o->listen_addr = abuf;
        o->listen_port = atoi(colon + 1);
    } else {
        o->listen_port = atoi(s);
    }
    if (o->listen_port <= 0 || o->listen_port > 65535) return -1;
    return 0;
}

int main(int argc, char **argv) {
    struct proxyd_opts o = {
        .listen_addr = "0.0.0.0",
        .listen_port = PROXYD_DEFAULT_PORT,
        .daemon_sock = PW_IPC_DEFAULT_PATH,
    };

    for (int i = 1; i < argc; i++) {
        const char *a = argv[i];
        if (!strcmp(a, "--listen") && i + 1 < argc) {
            if (parse_listen(&o, argv[++i]) != 0) {
                fprintf(stderr, "proxyd: bad --listen\n");
                return 2;
            }
        } else if (!strcmp(a, "--socket") && i + 1 < argc) {
            o.daemon_sock = argv[++i];
        } else if (!strcmp(a, "--tls-cert") && i + 1 < argc) {
            o.tls_cert = argv[++i];
        } else if (!strcmp(a, "--tls-key") && i + 1 < argc) {
            o.tls_key = argv[++i];
        } else if (!strcmp(a, "--no-tls")) {
            o.no_tls = true;
        } else if (!strcmp(a, "--insecure-no-auth")) {
            o.insecure_no_auth = true;
        } else if (!strcmp(a, "-h") || !strcmp(a, "--help")) {
            usage();
            return 0;
        } else {
            fprintf(stderr, "proxyd: unknown arg '%s'\n", a);
            usage();
            return 2;
        }
    }
    if ((o.tls_cert && !o.tls_key) || (!o.tls_cert && o.tls_key)) {
        fprintf(stderr, "proxyd: --tls-cert and --tls-key must be paired\n");
        return 2;
    }

    signal(SIGPIPE, SIG_IGN);
    g_daemon_sock = o.daemon_sock;

    /* Resolve the listen address to a numeric IPv4 up front. We only bind
     * AF_INET, so reject anything inet_pton can't parse (e.g. an IPv6 literal
     * or a hostname) rather than silently falling back to 0.0.0.0 -- that
     * fallback would turn a "loopback-looking" --listen into a public bind. */
    struct in_addr listen_ia;
    if (inet_pton(AF_INET, o.listen_addr, &listen_ia) != 1) {
        fprintf(stderr, "proxyd: --listen address must be a numeric IPv4 "
                        "address (got '%s'); IPv6/hostnames are not supported\n",
                o.listen_addr);
        return 2;
    }
    bool loopback = (ntohl(listen_ia.s_addr) >> 24) == 127; /* 127.0.0.0/8 */

    printf("packetwyrm-proxyd starting\n");
    printf("  daemon socket: %s\n", o.daemon_sock);

    /* Auth safeguard: on a non-loopback bind, only proceed if the daemon is
     * KNOWN to require a secret (sec == 1). If it has none (sec == 0) or we
     * can't tell because it's unreachable at startup (sec == -1), fail CLOSED
     * -- otherwise a no-secret daemon coming up later would be exposed. */
    int sec = probe_daemon_secret();
    if (!loopback && !o.insecure_no_auth && sec != 1) {
        fprintf(stderr,
            "proxyd: REFUSING to bind %s:%d -- %s, so a public bind could "
            "expose full control.\n"
            "        Set system.secret in the daemon env config, bind "
            "127.0.0.1, or pass --insecure-no-auth to override.\n",
            o.listen_addr, o.listen_port,
            sec == 0 ? "the daemon has no secret configured"
                     : "the daemon is unreachable so its auth can't be confirmed");
        return 1;
    }
    if (sec == -1)
        fprintf(stderr, "  warning: daemon not reachable at startup "
                        "(will relay once it is up)\n");
    else
        printf("  daemon auth: %s\n", sec == 1 ? "secret required" : "OPEN (no secret)");

    /* TLS. */
    if (!o.no_tls) {
        g_ssl_ctx = tls_ctx_new(&o);
        if (!g_ssl_ctx) return 1;
    } else {
        printf("  TLS: DISABLED (--no-tls, plaintext)\n");
    }

    /* Listen socket. */
    int lfd = socket(AF_INET, SOCK_STREAM | SOCK_CLOEXEC, 0);
    if (lfd < 0) { perror("socket"); return 1; }
    int one = 1;
    setsockopt(lfd, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));
    struct sockaddr_in sa = { .sin_family = AF_INET,
                              .sin_port = htons((uint16_t)o.listen_port),
                              .sin_addr = listen_ia };
    if (bind(lfd, (struct sockaddr *)&sa, sizeof(sa)) < 0) {
        perror("bind");
        return 1;
    }
    if (listen(lfd, 16) < 0) { perror("listen"); return 1; }
    printf("  listening on %s://%s:%d/\n", o.no_tls ? "http" : "https",
           o.listen_addr, o.listen_port);
    fflush(stdout);

    for (;;) {
        int cfd = accept(lfd, NULL, NULL);
        if (cfd < 0) {
            if (errno == EINTR) continue;
            perror("accept");
            break;
        }
        if (atomic_load(&g_active_threads) >= PROXYD_MAX_THREADS) {
            struct conn c = { .fd = cfd, .ssl = NULL };
            /* Can't cheaply TLS-negotiate here; just drop over plaintext. */
            if (!g_ssl_ctx) http_error(&c, 503, "too many connections");
            close(cfd);
            continue;
        }
        atomic_fetch_add(&g_active_threads, 1);
        pthread_t th;
        if (pthread_create(&th, NULL, worker, (void *)(intptr_t)cfd) != 0) {
            atomic_fetch_sub(&g_active_threads, 1);
            close(cfd);
            continue;
        }
        pthread_detach(th);
    }

    close(lfd);
    if (g_ssl_ctx) SSL_CTX_free(g_ssl_ctx);
    return 0;
}
