#!/usr/bin/env python3
"""Generate proxyd_assets.h: embed the GUI asset tree as a C blob table.

Replaces the old single-file `xxd -i index.html`. Walks an assets directory and
emits, for each file, a byte array plus a table entry
{ url_path, data, len, content_type }. proxyd serves GET <url_path> by an exact
table lookup (no filesystem access -> path traversal is structurally impossible).

Usage: gen_assets.py <assets_dir> <output_header>

Deterministic: files are walked in sorted order so the generated header is
reproducible across builds.
"""
import os
import sys

# Extension -> Content-Type. Anything unlisted falls back to octet-stream.
CTYPE = {
    ".html": "text/html; charset=utf-8",
    ".css":  "text/css; charset=utf-8",
    ".js":   "text/javascript; charset=utf-8",
    ".mjs":  "text/javascript; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".map":  "application/json; charset=utf-8",
    ".svg":  "image/svg+xml",
    ".ico":  "image/x-icon",
    ".png":  "image/png",
    ".woff2": "font/woff2",
    ".txt":  "text/plain; charset=utf-8",
    ".license": "text/plain; charset=utf-8",
}


def ctype_for(path):
    _, ext = os.path.splitext(path)
    return CTYPE.get(ext.lower(), "application/octet-stream")


def c_str(s):
    # Escape a string for a C string literal (paths/content-types are ASCII).
    return s.replace("\\", "\\\\").replace('"', '\\"')


def c_escape_bytes(data):
    # Emit as a comma-separated list of decimal bytes, wrapped for readability.
    out = []
    for i in range(0, len(data), 20):
        chunk = data[i:i + 20]
        out.append(",".join(str(b) for b in chunk))
    return ",\n  ".join(out)


def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: gen_assets.py <assets_dir> <output_header>\n")
        return 2
    assets_dir = os.path.abspath(sys.argv[1])
    out_path = sys.argv[2]

    files = []
    for root, dirs, names in os.walk(assets_dir):
        dirs.sort()
        for name in sorted(names):
            full = os.path.join(root, name)
            rel = os.path.relpath(full, assets_dir)
            url = "/" + rel.replace(os.sep, "/")
            files.append((url, full))
    files.sort(key=lambda x: x[0])

    lines = []
    lines.append("/* Generated by gen_assets.py -- do NOT edit. Embeds the GUI asset tree. */")
    lines.append("#ifndef PROXYD_ASSETS_H")
    lines.append("#define PROXYD_ASSETS_H")
    lines.append("#include <stddef.h>")
    lines.append("")

    entries = []
    for idx, (url, full) in enumerate(files):
        with open(full, "rb") as f:
            data = f.read()
        sym = "pw_asset_%d" % idx
        lines.append("static const unsigned char %s[] = {" % sym)
        if data:
            lines.append("  " + c_escape_bytes(data))
        lines.append("};")
        entries.append((url, sym, len(data), ctype_for(url)))

    lines.append("")
    lines.append("struct pw_asset { const char *path; const unsigned char *data; size_t len; const char *ctype; };")
    lines.append("static const struct pw_asset pw_assets[] = {")
    for url, sym, ln, ct in entries:
        lines.append('  { "%s", %s, %d, "%s" },' % (c_str(url), sym, ln, c_str(ct)))
    lines.append("};")
    lines.append("static const size_t pw_assets_n = sizeof(pw_assets) / sizeof(pw_assets[0]);")
    lines.append("")
    lines.append("#endif /* PROXYD_ASSETS_H */")

    text = "\n".join(lines) + "\n"
    # Write only if changed: this script runs on every build (FORCE dep) so the
    # header reflects asset additions AND deletions, but we avoid touching its
    # mtime (and needlessly relinking proxyd) when nothing changed.
    try:
        with open(out_path, "r") as f:
            if f.read() == text:
                return 0
    except FileNotFoundError:
        pass
    with open(out_path, "w") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
