/* Vector generator for the C-side ↔ RTL-side wire-format check.
 *
 * Opens a 64 KB tmpfs file as a synthetic BAR0, runs the real
 * pw_bar_backend ops to program a known classifier and flow entry,
 * then dumps the BAR image as a Verilog $readmemh-friendly hex
 * file (one 32-bit dword per line, dword 0 first). The companion
 * RTL TB in sim/wire_vectors_tb replays the dwords through
 * pw_csr_window as if they were AXI-Lite writes and verifies the
 * decoded classifier table matches the expected fields.
 *
 * Usage:
 *   build/gen_bar_vectors <out.hex>
 *
 * The dumped file is the byte-for-byte contract between csr.h on
 * the host side and pw_classifier_window / pw_flow_window on the
 * RTL side. If either side drifts (struct layout change, mask
 * shift, etc.), the vector file diff catches it. */

#include <fcntl.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

#include "packetwyrm/packetwyrm.h"

#define BAR_SIZE 65536u

int main(int argc, char **argv) {
    if (argc != 2) {
        fprintf(stderr, "usage: %s <out.hex>\n", argv[0]);
        return 2;
    }
    const char *out_path = argv[1];

    char tmp_path[] = "/tmp/pw_vec_XXXXXX";
    int fd = mkstemp(tmp_path);
    if (fd < 0) { perror("mkstemp"); return 1; }
    if (ftruncate(fd, BAR_SIZE) < 0) { perror("ftruncate"); close(fd); return 1; }
    close(fd);

    struct pw_card_backend b;
    pw_status r = pw_bar_backend_open_path(tmp_path, &b);
    if (r != PW_OK) {
        fprintf(stderr, "bar_backend_open_path: %s\n", pw_strerror(r));
        unlink(tmp_path);
        return 1;
    }

    /* (The legacy classifier table is retired; this golden image now exercises
     * the flow-window byte layout only. The field/hash classifier programming
     * is register-based and covered by tb_field_classifier / tb_hash_classifier
     * + tb_csr_full.) */

    /* Flow row 0: bind egress port 0 with a known rate. */
    struct pwfpga_flow_config fc = {0};
    fc.enable             = 1;
    fc.egress_local_port  = 0;
    fc.global_flow_id     = 42;
    fc.local_flow_id      = 0;
    fc.dst_mac[0]=0x02; fc.dst_mac[1]=0xa5; fc.dst_mac[2]=0x02;
    fc.dst_mac[3]=0x00; fc.dst_mac[4]=0x00; fc.dst_mac[5]=0x02;
    fc.src_mac[0]=0x02; fc.src_mac[1]=0xa5; fc.src_mac[2]=0x02;
    fc.src_mac[3]=0x00; fc.src_mac[4]=0x00; fc.src_mac[5]=0x01;
    fc.src_ipv4          = 0xC0000201u;
    fc.dst_ipv4          = 0xC0000202u;
    fc.udp_src_port      = 49152;
    fc.udp_dst_port      = 50001;
    fc.tokens_per_tick_fp = 0x00040000u;
    fc.burst_bytes        = 256;
    fc.tx_enable         = 1;
    /* New 238-byte-row fields: unique non-zero patterns so the RTL decode of the
     * IPv6 mask-hi byte order is checked too. */
    for (int i = 0; i < 12; i++) {
        fc.src_ipv6_mask_hi[i] = (uint8_t)(0xA0 + i);
        fc.dst_ipv6_mask_hi[i] = (uint8_t)(0xB0 + i);
    }
    if ((r = b.ops->flow_write(b.ctx, 0, &fc)) != PW_OK) {
        fprintf(stderr, "flow_write: %s\n", pw_strerror(r));
        goto fail;
    }
    if ((r = b.ops->flow_commit(b.ctx)) != PW_OK) {
        fprintf(stderr, "flow_commit: %s\n", pw_strerror(r));
        goto fail;
    }

    /* Re-mmap to grab the post-write image. The BAR backend uses
     * MAP_SHARED so the kernel has already pushed the writes to
     * the underlying tmpfs file. */
    int rfd = open(tmp_path, O_RDONLY);
    if (rfd < 0) { perror("open"); goto fail; }
    uint8_t *img = mmap(NULL, BAR_SIZE, PROT_READ, MAP_SHARED, rfd, 0);
    close(rfd);
    if (img == MAP_FAILED) { perror("mmap"); goto fail; }

    FILE *fp = fopen(out_path, "w");
    if (!fp) { perror("fopen"); munmap(img, BAR_SIZE); goto fail; }
    fprintf(fp, "// PacketWyrm BAR image, %u dwords (= %u bytes).\n",
            BAR_SIZE / 4, BAR_SIZE);
    fprintf(fp, "// Generated by gen_bar_vectors. DO NOT EDIT.\n");
    for (size_t i = 0; i < BAR_SIZE; i += 4) {
        uint32_t v;
        memcpy(&v, img + i, 4);
        fprintf(fp, "%08x\n", v);
    }
    fclose(fp);
    munmap(img, BAR_SIZE);

    pw_card_backend_close(&b);
    unlink(tmp_path);
    printf("wrote %s (%u dwords)\n", out_path, BAR_SIZE / 4);
    return 0;

fail:
    pw_card_backend_close(&b);
    unlink(tmp_path);
    return 1;
}
