#!/usr/bin/env bash
# Verilator lint of the AS02MC04 Phase 1 RTL.
# Uses xilinx_prims_blackbox.sv so Vivado UNISIM primitives compile
# off-Vivado; the real `unisims` library is picked up at synthesis.

set -euo pipefail

script_dir=$(cd "$(dirname "$0")" && pwd)
repo_root=$(cd "$script_dir/../../.." && pwd)
tmp_ver=$(mktemp --suffix=.sv)
trap 'rm -f "$tmp_ver"' EXIT

# pw_version_pkg is generated by Vivado; produce a stable one for lint.
sed -e 's/@PW_VERSION@/00010000/' \
    -e 's/@PW_BUILD_ID@/FACE0000/' \
    -e 's/@PW_GIT_HASH@/DEADBEEF/' \
    "$repo_root/rtl/shared/pw_version_pkg.sv.in" > "$tmp_ver"

verilator --lint-only --top-module pwfpga_top_phase1 \
    -Wall \
    -Wno-DECLFILENAME -Wno-UNUSEDSIGNAL -Wno-UNUSEDPARAM -Wno-PINCONNECTEMPTY \
    "$repo_root/rtl/shared/pw_pkg.sv" \
    "$tmp_ver" \
    "$repo_root/rtl/shared/xilinx_prims_blackbox.sv" \
    "$repo_root/rtl/shared/pw_heartbeat.sv" \
    "$repo_root/rtl/shared/pw_timestamp.sv" \
    "$repo_root/rtl/shared/pw_csr_min.sv" \
    "$repo_root/fpga/as02mc04/src/pcie_gen3_stub.sv" \
    "$repo_root/fpga/as02mc04/src/pcie_axi_lite_bridge.sv" \
    "$repo_root/fpga/as02mc04/src/clock_reset.sv" \
    "$repo_root/fpga/as02mc04/src/pwfpga_top_phase1.sv"

echo "lint OK"
