// Wire-format byte-vector regression.
//
// Loads `sim/vectors/bar_image.hex` (generated by the C-side
// `gen_bar_vectors` against the real pw_bar_backend), replays
// the non-zero dwords as AXI-Lite-style writes into the same
// pw_csr_full slave the production RTL ships, and verifies the
// classifier table and flow generator inputs decoded from those
// bytes match the host's intent. If either side (csr.h struct
// layout, classifier_window byte offsets, flow_window byte
// offsets) drifts, this test fails before silicon ever boots.

`default_nettype none

import pw_classifier_pkg::*;
import pw_axis_pkg::*;

module tb_wire_vectors;

    localparam int NUM_PORTS = 2;
    localparam int NUM_FLOWS = 8;
    localparam int NUM_HIST  = 16;
    localparam int ADDR_W    = 16;
    localparam int N_DWORDS  = 65536 / 4;

    logic clk = 0; always #5 clk = ~clk;
    logic rst_n = 0;

    // AXI-Lite slave
    logic [ADDR_W-1:0] awaddr;  logic awvalid; logic awready;
    logic [31:0]       wdata;   logic [3:0] wstrb; logic wvalid; logic wready;
    logic [1:0]        bresp;   logic bvalid; logic bready;
    logic [ADDR_W-1:0] araddr;  logic arvalid; logic arready;
    logic [31:0]       rdata;   logic [1:0] rresp; logic rvalid; logic rready;

    logic [63:0] ts;
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) ts <= '0; else ts <= ts + 64'd1;
    end

    logic [31:0] port_drops      [NUM_PORTS];
    logic [47:0] ps_zero         [NUM_PORTS] = '{default: 48'd0};  // port stats not exercised here
    logic [31:0] pl_zero         [NUM_PORTS] = '{default: 32'd0};  // link-health counts not exercised here
    logic [47:0] ftx_zero        [NUM_FLOWS] = '{default: 48'd0};  // per-flow tx not exercised here
    logic [63:0] fjit_zero       [NUM_FLOWS] = '{default: 64'd0};  // per-flow jitter sum not exercised here
    logic [31:0] fjit32_zero     [NUM_FLOWS] = '{default: 32'd0};  // per-flow jitter min/max not exercised here
    logic [63:0] flow_rx         [NUM_FLOWS];
    logic [63:0] flow_lost       [NUM_FLOWS];
    logic [63:0] flow_dup        [NUM_FLOWS];
    logic [63:0] flow_ooo        [NUM_FLOWS];
    logic [63:0] flow_last_seq   [NUM_FLOWS];
    logic [63:0] flow_min_lat    [NUM_FLOWS];
    logic [63:0] flow_max_lat    [NUM_FLOWS];
    logic [63:0] flow_sum_lat    [NUM_FLOWS];
    logic [63:0] flow_samples    [NUM_FLOWS];
    // Histogram is BRAM-backed in the data plane now; this TB exercises
    // the register/window wire format only, so tie the read data low.
    logic [63:0] hist_rd_data_w = '0;

    // The flow table is BRAM-backed (in the data plane). Feed csr_full's flow
    // write strobe into a flow_table_bram here so the C BAR image's flow-row
    // bytes are still cross-checked against the RTL decode.
    logic                          fwen;
    logic [ADDR_W-1:0]             fwaddr;
    logic [31:0]                   fwdata;
    pw_flow_sched_t                ft_sched [NUM_FLOWS];
    logic [$clog2(NUM_FLOWS)-1:0]  ft_rd_addr [NUM_PORTS];
    pw_flow_row_t                  ft_rd_row  [NUM_PORTS];
    pw_flow_table_bram #(
        .ADDR_W(ADDR_W), .DEPTH(NUM_FLOWS), .PORTS(NUM_PORTS),
        .WIN_BASE(16'h6000), .COMMIT_OFFSET(16'h3FFC)
    ) u_ft (
        .clk(clk), .rst_n(rst_n),
        .wr_en(fwen), .wr_addr(fwaddr), .wr_data(fwdata),
        .flow_sched_o(ft_sched), .rd_addr_i(ft_rd_addr), .rd_row_o(ft_rd_row),
        .commit_pulse_o()
    );

    pw_csr_full #(
        .ADDR_W         (ADDR_W),
        .NUM_PORTS      (NUM_PORTS),
        .NUM_FLOWS      (NUM_FLOWS),
        .NUM_CLASSIFIER (8),
        .NUM_HIST_BINS  (NUM_HIST)
    ) dut (
        .s_axi_aclk     (clk),
        .s_axi_aresetn  (rst_n),
        .s_axi_awaddr   (awaddr),
        .s_axi_awvalid  (awvalid),
        .s_axi_awready  (awready),
        .s_axi_wdata    (wdata),
        .s_axi_wstrb    (wstrb),
        .s_axi_wvalid   (wvalid),
        .s_axi_wready   (wready),
        .s_axi_bresp    (bresp),
        .s_axi_bvalid   (bvalid),
        .s_axi_bready   (bready),
        .s_axi_araddr   (araddr),
        .s_axi_arvalid  (arvalid),
        .s_axi_arready  (arready),
        .s_axi_rdata    (rdata),
        .s_axi_rresp    (rresp),
        .s_axi_rvalid   (rvalid),
        .s_axi_rready   (rready),
        .timestamp_i    (ts),
        .global_control_o    (),
        .error_status_set_i  (32'h0),
        .gpio_sync_ctrl_o    (),
        .gpio_sync_ts_i      (64'h0),
        .gpio_sync_seq_i     (32'h0),
        .gpio_sync_gpio_in_i (6'h0),
        .port_drops_i        (port_drops),
        .rx_frames_i         (ps_zero),
        .rx_bytes_i          (ps_zero),
        .tx_frames_i         (ps_zero),
        .tx_bytes_i          (ps_zero),
        .rx_fcs_err_i        (ps_zero),
        .link_up_cnt_i       (pl_zero),
        .link_down_cnt_i     (pl_zero),
        .block_lock_loss_i   (pl_zero),
        .flow_rd_addr_o      (),                // flow stats not exercised here
        .flow_rx_i           (64'd0),
        .flow_lost_i         (64'd0),
        .flow_dup_i          (64'd0),
        .flow_ooo_i          (64'd0),
        .flow_last_seq_i     (64'd0),
        .flow_min_lat_i      (64'd0),
        .flow_max_lat_i      (64'd0),
        .flow_sum_lat_i      (64'd0),
        .flow_samples_i      (64'd0),
        .flow_jit_min_i      (32'd0),
        .flow_jit_max_i      (32'd0),
        .flow_jit_sum_i      (64'd0),
        .flow_tx_i           (48'd0),
        .hist_rd_addr_o      (),
        .hist_rd_data_i      (hist_rd_data_w),
        .flow_wr_en_o        (fwen),
        .flow_wr_addr_o      (fwaddr),
        .flow_wr_data_o      (fwdata),
        .map_wr_en_o         (),
        .map_wr_addr_o       (),
        .map_wr_valid_o      (),
        .map_wr_lfid_o       (),
        .cmp_wr_en_o         (),
        .cmp_wr_idx_o        (),
        .cmp_wr_src_o        (),
        .cmp_wr_mask_o       (),
        .cmp_wr_value_o      (),
        .udf_wr_en_o         (),
        .udf_wr_idx_o        (),
        .udf_wr_offset_o     (),
        .udf_wr_mask_o       (),
        .udf_wr_value_o      (),
        .rule_wr_en_o        (),
        .rule_wr_idx_o       (),
        .rule_wr_care_o      (),
        .rule_wr_action_o    (),
        .rule_wr_egress_o    (),
        .rule_wr_lfid_o      (),
        .rule_wr_lif_o       (),
        .rule_wr_prio_o      (),
        .rule_wr_enable_o    (),
        .hash_seed_o         (),
        .hash_mask_o         (),
        .hash_wr_en_o        (),
        .hash_wr_index_o     (),
        .hash_wr_valid_o     (),
        .hash_wr_key_o       (),
        .hash_wr_lfid_o      (),
        .stats_clear_o       (),
        .dp_soft_rst_o       (),
        .spi_sck_o           (),
        .spi_cs_n_o          (),
        .spi_mosi_o          (),
        .spi_miso_i          (1'b0),
        .icap_reboot_o       (),
        .punt_rd_en_o        (),
        .punt_rd_addr_o      (),
        .punt_rd_data_i      (32'h0),
        .punt_pop_o          (),
        .inj_m_tdata         (),
        .inj_m_tkeep         (),
        .inj_m_tvalid        (),
        .inj_m_tready        (1'b1),
        .inj_m_tlast         (),
        .inj_egress_o        ()
    );

    int    errors = 0;
    string scenario = "init";

    task automatic check_eq(string what, longint got, longint exp);
        if (got != exp) begin
            $display("[FAIL %s] %s: got=%0d expected=%0d",
                     scenario, what, got, exp);
            errors++;
        end else begin
            $display("[ ok %s] %s: %0d", scenario, what, got);
        end
    endtask

    task automatic axi_write(input logic [ADDR_W-1:0] addr,
                              input logic [31:0]       data);
        @(posedge clk);
        awaddr  = addr;
        awvalid = 1'b1;
        wdata   = data;
        wstrb   = 4'hF;
        wvalid  = 1'b1;
        bready  = 1'b1;
        do @(posedge clk); while (!bvalid);
        awvalid = 1'b0;
        wvalid  = 1'b0;
        bready  = 1'b0;
    endtask

    logic [31:0] image [0:N_DWORDS-1];

    initial begin
        for (int i = 0; i < N_DWORDS; i++) image[i] = '0;
        $readmemh("vectors/bar_image.hex", image);

        awaddr = '0; awvalid = 0;
        wdata  = '0; wstrb = 4'hF; wvalid = 0;
        bready = 0;
        araddr = '0; arvalid = 0; rready = 0;
        for (int p = 0; p < NUM_PORTS; p++) port_drops[p] = '0;
        for (int f = 0; f < NUM_FLOWS; f++) begin
            flow_rx[f]=0; flow_lost[f]=0; flow_dup[f]=0; flow_ooo[f]=0;
            flow_last_seq[f]=0; flow_min_lat[f]=0; flow_max_lat[f]=0;
            flow_sum_lat[f]=0; flow_samples[f]=0;
        end

        repeat (8) @(posedge clk);
        rst_n = 1;
        @(posedge clk);

        // ---- replay every non-zero dword in the classifier and
        //      flow window regions as an AXI-Lite write. Identity
        //      registers (offset < 0x2000) are read-only; skip them.
        //      The wide map puts classifier at 0x2000..0x5FFF and the
        //      flow window at 0x6000..0x9FFF (commit regs at 0x5FFC /
        //      0x9FFC); replay that whole span. ----
        scenario = "replay";
        begin
            int writes;
            writes = 0;
            for (int i = 16'h2000 / 4; i < 16'hA000 / 4; i++) begin
                if (image[i] != 32'h0) begin
                    axi_write(16'(i * 4), image[i]);
                    writes++;
                end
            end
            $display("[info replay] %0d non-zero dwords applied", writes);
            check_eq("at least one write happened", (writes > 0) ? 1 : 0, 1);
        end

        // Give a couple cycles for commit pulses to land.
        repeat (4) @(posedge clk);

        // The legacy classifier table window (0x2000) is retired (replaced by the
        // field+UDF classifier, programmed comparator/rule-wise -- exercised by
        // tb_field_classifier + tb_data_plane_axis + tb_phase3_top). The golden
        // image's old classifier bytes still replay harmlessly above (unconnected
        // field-classifier write ports). This vector test now covers the flow
        // window layout only.

        // ---- verify the C image's flow row decoded by the BRAM flow table ----
        scenario = "flow";
        // The vector programs flow row 0 on egress port 0 and commits; the BRAM
        // table walks it in. The staging is now a 32-bit-word BRAM walked one
        // word per cycle, so the walk takes NUM_FLOWS*ROW_DW (=64) cycles.
        ft_rd_addr[0] = '0; ft_rd_addr[1] = '0;
        repeat (NUM_FLOWS*64 + 16) @(posedge clk);
        check_eq("flow0 valid",     ft_sched[0].valid ? 1 : 0, 1);
        check_eq("flow0 egress",    ft_sched[0].egress, 0);
        check_eq("tokens_per_tick", ft_sched[0].tokens_fp, 32'h00040000);
        check_eq("cap (burst<<16)", ft_sched[0].cap, {16'd256, 16'h0});
        check_eq("src_ip",          ft_rd_row[0].src_ipv4, 32'hC000_0201);
        check_eq("dst_ip",          ft_rd_row[0].dst_ipv4, 32'hC000_0202);
        check_eq("udp_src",         ft_rd_row[0].udp_sp, 49152);
        check_eq("udp_dst",         ft_rd_row[0].udp_dp, 50001);
        check_eq("smac",            ft_rd_row[0].src_mac, 48'h02_a5_02_00_00_01);
        check_eq("dmac",            ft_rd_row[0].dst_mac, 48'h02_a5_02_00_00_02);
        // New 240-byte-row fields: l4_proto (6=TCP), tcp_flags, and the IPv6
        // mask-hi (little-endian byte order: byte 0 = bits [7:0] = 0xA0/0xB0).
        check_eq("l4_proto (TCP)",  ft_rd_row[0].l4_proto, 8'd6);
        check_eq("tcp_flags",       ft_rd_row[0].tcp_flags, 8'h12);
        check_eq("sip_mask_hi",     ft_rd_row[0].sip_mask_hi,
                 96'hAB_AA_A9_A8_A7_A6_A5_A4_A3_A2_A1_A0);
        check_eq("dip_mask_hi",     ft_rd_row[0].dip_mask_hi,
                 96'hBB_BA_B9_B8_B7_B6_B5_B4_B3_B2_B1_B0);

        if (errors == 0) begin
            $display("ALL WIRE VECTOR SCENARIOS PASS");
            $finish;
        end else begin
            $display("FAILED with %0d error(s)", errors);
            $fatal;
        end
    end

    initial begin
        #1000000;
        $display("WATCHDOG TIMEOUT");
        $fatal;
    end

endmodule

`default_nettype wire
