// Wire-format byte-vector regression.
//
// Loads `sim/vectors/bar_image.hex` (generated by the C-side
// `gen_bar_vectors` against the real pw_bar_backend), replays
// the non-zero dwords as AXI-Lite-style writes into the same
// pw_csr_full slave the production RTL ships, and verifies the
// classifier table and flow generator inputs decoded from those
// bytes match the host's intent. If either side (csr.h struct
// layout, classifier_window byte offsets, flow_window byte
// offsets) drifts, this test fails before silicon ever boots.

`default_nettype none

import pw_classifier_pkg::*;

module tb_wire_vectors;

    localparam int NUM_PORTS = 2;
    localparam int NUM_FLOWS = 8;
    localparam int NUM_HIST  = 16;
    localparam int ADDR_W    = 16;
    localparam int N_DWORDS  = 65536 / 4;

    logic clk = 0; always #5 clk = ~clk;
    logic rst_n = 0;

    // AXI-Lite slave
    logic [ADDR_W-1:0] awaddr;  logic awvalid; logic awready;
    logic [31:0]       wdata;   logic [3:0] wstrb; logic wvalid; logic wready;
    logic [1:0]        bresp;   logic bvalid; logic bready;
    logic [ADDR_W-1:0] araddr;  logic arvalid; logic arready;
    logic [31:0]       rdata;   logic [1:0] rresp; logic rvalid; logic rready;

    logic [63:0] ts;
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) ts <= '0; else ts <= ts + 64'd1;
    end

    logic [31:0] port_drops      [NUM_PORTS];
    logic [63:0] flow_rx         [NUM_FLOWS];
    logic [63:0] flow_lost       [NUM_FLOWS];
    logic [63:0] flow_dup        [NUM_FLOWS];
    logic [63:0] flow_ooo        [NUM_FLOWS];
    logic [63:0] flow_last_seq   [NUM_FLOWS];
    logic [63:0] flow_min_lat    [NUM_FLOWS];
    logic [63:0] flow_max_lat    [NUM_FLOWS];
    logic [63:0] flow_sum_lat    [NUM_FLOWS];
    logic [63:0] flow_samples    [NUM_FLOWS];
    // Histogram is BRAM-backed in the data plane now; this TB exercises
    // the register/window wire format only, so tie the read data low.
    logic [63:0] hist_rd_data_w = '0;

    pw_classifier_table_t          cls_table;
    logic [NUM_PORTS-1:0]          gen_enable_w;
    logic [NUM_PORTS-1:0] [31:0]   gen_tokens_w;
    logic [NUM_PORTS-1:0] [15:0]   gen_burst_w;
    logic [NUM_PORTS-1:0] [47:0]   gen_smac_w;
    logic [NUM_PORTS-1:0] [47:0]   gen_dmac_w;
    logic [NUM_PORTS-1:0]          gen_vlan_en_w;
    logic [NUM_PORTS-1:0] [11:0]   gen_vlan_id_w;
    logic [NUM_PORTS-1:0] [31:0]   gen_sip_w;
    logic [NUM_PORTS-1:0] [31:0]   gen_dip_w;
    logic [NUM_PORTS-1:0] [15:0]   gen_usp_w;
    logic [NUM_PORTS-1:0] [15:0]   gen_udp_w;

    pw_csr_full #(
        .ADDR_W         (ADDR_W),
        .NUM_PORTS      (NUM_PORTS),
        .NUM_FLOWS      (NUM_FLOWS),
        .NUM_CLASSIFIER (8),
        .NUM_HIST_BINS  (NUM_HIST)
    ) dut (
        .s_axi_aclk     (clk),
        .s_axi_aresetn  (rst_n),
        .s_axi_awaddr   (awaddr),
        .s_axi_awvalid  (awvalid),
        .s_axi_awready  (awready),
        .s_axi_wdata    (wdata),
        .s_axi_wstrb    (wstrb),
        .s_axi_wvalid   (wvalid),
        .s_axi_wready   (wready),
        .s_axi_bresp    (bresp),
        .s_axi_bvalid   (bvalid),
        .s_axi_bready   (bready),
        .s_axi_araddr   (araddr),
        .s_axi_arvalid  (arvalid),
        .s_axi_arready  (arready),
        .s_axi_rdata    (rdata),
        .s_axi_rresp    (rresp),
        .s_axi_rvalid   (rvalid),
        .s_axi_rready   (rready),
        .timestamp_i    (ts),
        .global_control_o    (),
        .error_status_set_i  (32'h0),
        .port_drops_i        (port_drops),
        .flow_rx_i           (flow_rx),
        .flow_lost_i         (flow_lost),
        .flow_dup_i          (flow_dup),
        .flow_ooo_i          (flow_ooo),
        .flow_last_seq_i     (flow_last_seq),
        .flow_min_lat_i      (flow_min_lat),
        .flow_max_lat_i      (flow_max_lat),
        .flow_sum_lat_i      (flow_sum_lat),
        .flow_samples_i      (flow_samples),
        .hist_rd_addr_o      (),
        .hist_rd_data_i      (hist_rd_data_w),
        .cls_table_o         (cls_table),
        .gen_enable_o        (gen_enable_w),
        .gen_tokens_fp_o     (gen_tokens_w),
        .gen_burst_o         (gen_burst_w),
        .gen_src_mac_o       (gen_smac_w),
        .gen_dst_mac_o       (gen_dmac_w),
        .gen_vlan_en_o       (gen_vlan_en_w),
        .gen_vlan_id_o       (gen_vlan_id_w),
        .gen_src_ip_o        (gen_sip_w),
        .gen_dst_ip_o        (gen_dip_w),
        .gen_udp_sp_o        (gen_usp_w),
        .gen_udp_dp_o        (gen_udp_w),
        .flow_rows_o         (),
        .stats_clear_o       ()
    );

    int    errors = 0;
    string scenario = "init";

    task automatic check_eq(string what, longint got, longint exp);
        if (got != exp) begin
            $display("[FAIL %s] %s: got=%0d expected=%0d",
                     scenario, what, got, exp);
            errors++;
        end else begin
            $display("[ ok %s] %s: %0d", scenario, what, got);
        end
    endtask

    task automatic axi_write(input logic [ADDR_W-1:0] addr,
                              input logic [31:0]       data);
        @(posedge clk);
        awaddr  = addr;
        awvalid = 1'b1;
        wdata   = data;
        wstrb   = 4'hF;
        wvalid  = 1'b1;
        bready  = 1'b1;
        do @(posedge clk); while (!bvalid);
        awvalid = 1'b0;
        wvalid  = 1'b0;
        bready  = 1'b0;
    endtask

    logic [31:0] image [0:N_DWORDS-1];

    initial begin
        for (int i = 0; i < N_DWORDS; i++) image[i] = '0;
        $readmemh("vectors/bar_image.hex", image);

        awaddr = '0; awvalid = 0;
        wdata  = '0; wstrb = 4'hF; wvalid = 0;
        bready = 0;
        araddr = '0; arvalid = 0; rready = 0;
        for (int p = 0; p < NUM_PORTS; p++) port_drops[p] = '0;
        for (int f = 0; f < NUM_FLOWS; f++) begin
            flow_rx[f]=0; flow_lost[f]=0; flow_dup[f]=0; flow_ooo[f]=0;
            flow_last_seq[f]=0; flow_min_lat[f]=0; flow_max_lat[f]=0;
            flow_sum_lat[f]=0; flow_samples[f]=0;
        end

        repeat (8) @(posedge clk);
        rst_n = 1;
        @(posedge clk);

        // ---- replay every non-zero dword in the classifier and
        //      flow window regions as an AXI-Lite write. Identity
        //      registers (offset < 0x1000) are read-only; skip
        //      them. Commit registers (0x1FFC, 0x2FFC) are part of
        //      the window range and get replayed too. ----
        scenario = "replay";
        begin
            int writes;
            writes = 0;
            for (int i = 16'h1000 / 4; i < 16'h3000 / 4; i++) begin
                if (image[i] != 32'h0) begin
                    axi_write(16'(i * 4), image[i]);
                    writes++;
                end
            end
            $display("[info replay] %0d non-zero dwords applied", writes);
            check_eq("at least one write happened", (writes > 0) ? 1 : 0, 1);
        end

        // Give a couple cycles for commit pulses to land.
        repeat (4) @(posedge clk);

        // ---- verify classifier row 1 ----
        scenario = "classifier";
        check_eq("row1 enable",     cls_table[1].enable ? 1 : 0, 1);
        check_eq("row1 action",     longint'(cls_table[1].action), 1);
        check_eq("row1 priority",   cls_table[1].priority_, 5);
        check_eq("row1 lfid",       cls_table[1].local_flow_id, 3);
        check_eq("row1 lif",        cls_table[1].logical_if_id, 1000);
        check_eq("row1 l3_proto",   cls_table[1].key.l3_proto, 17);
        check_eq("row1 l4_dst",     cls_table[1].key.l4_dst, 50001);
        check_eq("row1 test_magic", cls_table[1].key.test_magic, 32'hA5027E57);
        check_eq("row1 flow_id",    cls_table[1].key.test_flow_id, 42);
        check_eq("row1 mask l3",    cls_table[1].mask.match_l3_proto ? 1:0, 1);
        check_eq("row1 mask l4",    cls_table[1].mask.match_l4_dst ? 1:0, 1);
        check_eq("row1 mask mg",    cls_table[1].mask.match_is_test ? 1:0, 1);
        check_eq("row1 mask fl",    cls_table[1].mask.match_flow_id ? 1:0, 1);
        // Row 0 stayed untouched (all zero).
        check_eq("row0 enable",     cls_table[0].enable ? 1 : 0, 0);

        // ---- verify flow window decoded into port 0 inputs ----
        scenario = "flow";
        check_eq("gen_enable[0]",   gen_enable_w[0] ? 1 : 0, 1);
        check_eq("gen_enable[1]",   gen_enable_w[1] ? 1 : 0, 0);
        check_eq("tokens_per_tick", gen_tokens_w[0], 32'h00040000);
        check_eq("burst",           gen_burst_w[0], 256);
        check_eq("src_ip",          gen_sip_w[0], 32'hC000_0201);
        check_eq("dst_ip",          gen_dip_w[0], 32'hC000_0202);
        check_eq("udp_src",         gen_usp_w[0], 49152);
        check_eq("udp_dst",         gen_udp_w[0], 50001);
        check_eq("smac",            gen_smac_w[0], 48'h02_a5_02_00_00_01);
        check_eq("dmac",            gen_dmac_w[0], 48'h02_a5_02_00_00_02);

        if (errors == 0) begin
            $display("ALL WIRE VECTOR SCENARIOS PASS");
            $finish;
        end else begin
            $display("FAILED with %0d error(s)", errors);
            $fatal;
        end
    end

    initial begin
        #1000000;
        $display("WATCHDOG TIMEOUT");
        $fatal;
    end

endmodule

`default_nettype wire
